import { ConflictException, BadRequestException } from '@nestjs/common';
import { AnnualPlanService } from './annual-plan.service';
import { ControlScopeService } from './control-scope.service';

describe('Annual plan explicit task assignment decisions', () => {
    let db: any;
    let service: AnnualPlanService;
    let tasks: any[];
    beforeEach(() => {
        const control = { id: 'c1', controlId: 'C1', name: 'Control', frequency: 'DAILY', selectedMonths: [] };
        const scope = { id: 's2027', controlId: 'c1', year: 2027, status: 'ACTIVE', frequency: 'DAILY', selectedMonths: [], assigneeId: null, secondControllerId: null, control };
        const item = { controlId: 'c1', inScope: true, frequency: 'DAILY', selectedMonths: [], assigneeId: 'new-first', secondControllerId: 'new-second' };
        tasks = ['BEKLIYOR', 'DEVAM_EDIYOR', 'TAMAMLANDI', 'GERI_GONDERILDI', 'ONAYLANDI'].map((status, i) => ({ id: `t${i}`, testNo: `T${i}`, scopeId: scope.id, status, isAutoGenerated: true, assigneeId: 'old-first', secondControllerId: 'old-second' }));
        tasks.push({ ...tasks[1], id: 'manual', isAutoGenerated: false });
        db = {
            annualPlanDraft: { findUnique: jest.fn().mockResolvedValue({ id: 'd2027', revision: 1, status: 'APPROVED', approvedRevision: 1 }), updateMany: jest.fn().mockResolvedValue({ count: 1 }) },
            annualPlanDraftItem: { findMany: jest.fn().mockResolvedValue([item]) },
            control: { findMany: jest.fn().mockResolvedValue([control]) },
            controlYearScope: { findMany: jest.fn().mockResolvedValue([scope]), findUnique: jest.fn().mockResolvedValue(scope), update: jest.fn(async ({ data }) => ({ ...scope, ...data })) },
            controlTest: {
                findMany: jest.fn(async ({ where }) => tasks.filter(t => t.scopeId === where.scopeId && (where.isAutoGenerated === undefined || t.isAutoGenerated === where.isAutoGenerated) && (!where.status || where.status.in.includes(t.status)))),
                updateMany: jest.fn(async ({ where, data }) => {
                    const matched = tasks.filter(t => where.id.in.includes(t.id) && (!where.status || where.status.in.includes(t.status)));
                    matched.forEach(t => Object.assign(t, data));
                    return { count: matched.length };
                }),
            },
            user: { findUnique: jest.fn().mockResolvedValue({ isActive: true, role: { permissions: ['control:*'] } }), findMany: jest.fn().mockResolvedValue([]) },
            auditLog: { create: jest.fn() },
        };
        db.$transaction = jest.fn(async fn => {
            const snapshot = structuredClone(tasks);
            try { return await fn(db); }
            catch (error) { tasks = snapshot; throw error; }
        });
        service = new AnnualPlanService(db, {} as any, new ControlScopeService(db));
    });
    const decisions = () => [
        { controlId: 'c1', taskId: 't1', action: 'REASSIGN' },
        { controlId: 'c1', taskId: 't2', action: 'KEEP' },
        { controlId: 'c1', taskId: 't3', action: 'REASSIGN' },
    ];
    it('requires explicit decisions and exposes the assignment conflict type', async () => {
        const preview = await service.previewApply(2027, 'actor', []);
        expect(preview.conflicts[0].type).toBe('ASSIGNMENT');
        expect(preview.conflicts[0].ongoingTasks).toHaveLength(3);
        expect((await service.applyPlan(2027, 'actor', [], { expectedRevision: 1 })).applied).toBe(false);
        expect(db.controlTest.updateMany).not.toHaveBeenCalled();
    });
    it('applies mixed KEEP/REASSIGN decisions while protecting approved and manual tasks', async () => {
        const result = await service.applyPlan(2027, 'actor', [], { expectedRevision: 1, assignmentDecisions: decisions() } as any);
        expect(result.applied).toBe(true);
        expect(tasks.filter(t => t.assigneeId === 'new-first').map(t => t.id)).toEqual(['t0', 't1', 't3']);
        expect(tasks.filter(t => t.assigneeId === 'old-first').map(t => t.id)).toEqual(['t2', 't4', 'manual']);
        expect(db.auditLog.create).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ action: 'ANNUAL_PLAN_APPLY', newValue: expect.objectContaining({ assignmentDecisions: decisions() }) }) }));
    });
    it('does not apply with a missing decision', async () => {
        const result = await service.applyPlan(2027, 'actor', [], { expectedRevision: 1, assignmentDecisions: decisions().slice(1) } as any);
        expect(result.applied).toBe(false);
        expect(db.$transaction).not.toHaveBeenCalled();
    });
    it.each(['unknown', 't4', 'manual'])('rejects an unrelated or protected task %s', async taskId => {
        await expect(service.applyPlan(2027, 'actor', [], { expectedRevision: 1, assignmentDecisions: [...decisions(), { controlId: 'c1', taskId, action: 'REASSIGN' }] } as any)).rejects.toThrow(BadRequestException);
        expect(db.$transaction).not.toHaveBeenCalled();
    });
    it('rejects duplicate decisions', async () => {
        await expect(service.applyPlan(2027, 'actor', [], { expectedRevision: 1, assignmentDecisions: [...decisions(), decisions()[0]] } as any)).rejects.toThrow(BadRequestException);
    });
    it('rejects decisions associated with a different control/year scope', async () => {
        const wrong = decisions().map(d => ({ ...d, controlId: 'another-year-control' }));
        await expect(service.applyPlan(2027, 'actor', [], { expectedRevision: 1, assignmentDecisions: wrong } as any)).rejects.toThrow(BadRequestException);
    });
    it('rejects an outdated draft revision', async () => {
        await expect(service.applyPlan(2027, 'actor', [], { expectedRevision: 0, assignmentDecisions: decisions() } as any)).rejects.toThrow(ConflictException);
        expect(db.$transaction).not.toHaveBeenCalled();
    });
    it('rolls back when a new task requiring a decision appears after preview', async () => {
        const original = db.$transaction.getMockImplementation();
        db.$transaction.mockImplementation(async fn => {
            tasks.push({ ...tasks[1], id: 'new-ongoing' });
            return original(fn);
        });
        await expect(service.applyPlan(2027, 'actor', [], { expectedRevision: 1, assignmentDecisions: decisions() } as any)).rejects.toThrow(ConflictException);
        expect(db.controlTest.updateMany).not.toHaveBeenCalled();
    });
    it('does not overwrite a task approved between reading and writing', async () => {
        const original = db.controlTest.updateMany.getMockImplementation();
        db.controlTest.updateMany.mockImplementation(async args => {
            if (args.where.id.in.includes('t1')) tasks[1].status = 'ONAYLANDI';
            return original(args);
        });
        await expect(service.applyPlan(2027, 'actor', [], { expectedRevision: 1, assignmentDecisions: decisions() } as any)).rejects.toThrow(ConflictException);
        expect(tasks.every(t => t.assigneeId === 'old-first')).toBe(true);
    });

    it('does not reassign a waiting task cancelled by the simultaneous schedule change', async () => {
        tasks[0].periodKey = 'M01'; // DAILY target schedule removes this old monthly task.
        const result = await service.applyPlan(2027, 'actor', [], { expectedRevision: 1, assignmentDecisions: decisions() } as any);
        expect(result.applied).toBe(true);
        expect(tasks[0].status).toBe('KAPSAM_DISI');
        expect(tasks[0].assigneeId).toBe('old-first');
    });

});
