import { Injectable, NotFoundException, BadRequestException } from '@nestjs/common';
import { PrismaService } from '../../prisma';
import { computeScopePeriods, computeMonthGroup, monthNumbersToLabels, ScopePeriod } from './control-period.util';
import { AddScopeDto, BulkAddScopeDto, ChangePeriodicityDto, CopyScopeDto, RemoveScopeDto } from './dto/control-scope.dto';
import { nextTestCode } from './test-code.util';

const LIVE_TASK_STATUSES_FREE = ['BEKLIYOR'];
const LIVE_TASK_STATUSES_DECISION = ['DEVAM_EDIYOR', 'TAMAMLANDI', 'GERI_GONDERILDI'];

/**
 * Kontrol–yıl ilişkisi (ControlYearScope) ve buna bağlı periyodik task
 * (ControlTest) üretimini yönetir. Control ana envanterdir ve burada
 * asla silinmez/mutasyona uğramaz — bu servis yalnızca kapsam ve task
 * yaşam döngüsüyle ilgilenir (bkz. plan "KONTROL ENVANTERİ").
 */
@Injectable()
export class ControlScopeService {
    constructor(private prisma: PrismaService) { }

    // ─── Yıl listesi (kod değişikliği gerektirmeden genişler) ────────────────
    async getScopeYears() {
        const currentYear = new Date().getFullYear();
        const base = [currentYear - 1, currentYear, currentYear + 1, currentYear + 2, currentYear + 3];
        const existing = await this.prisma.controlYearScope.findMany({ select: { year: true }, distinct: ['year'] });
        const set = new Set<number>([...base, ...existing.map(e => e.year)]);
        return { years: Array.from(set).sort((a, b) => a - b) };
    }

    // ─── Task üretimi (paylaşılan, eşzamanlılığa dayanıklı) ──────────────────
    /** createMany + skipDuplicates: (scopeId,periodKey) DB kısıtı sayesinde
     * tekrarlı/eşzamanlı çağrılar mükerrer task üretmez (P2002 yerine sessiz atlama). */
    private async generateTasksForPeriods(
        tx: any,
        scope: { id: string; year: number; assigneeId?: string | null; secondControllerId?: string | null },
        control: { id: string; controlId: string; type: string; ownerId: string; directorateId: string | null },
        periods: ScopePeriod[],
    ): Promise<number> {
        if (periods.length === 0) return 0;
        // testNo: (control,year) bazlı atomik sayaç — RecordCounter üzerinden
        // her çağrı gerçek, taahhüt-beklemeyen bir artış görür (bkz. test-code.util.ts).
        const rows: any[] = [];
        for (const p of periods) {
            const year = p.targetDate.getFullYear();
            const testNo = await nextTestCode(tx, control.id, control.controlId, year);
            rows.push({
                testNo, controlId: control.id, scopeId: scope.id, year: scope.year,
                periodKey: p.periodKey, periodLabel: p.periodLabel, periodStart: p.start, periodEnd: p.end,
                plannedDate: p.targetDate, isAutoGenerated: true, status: 'BEKLIYOR' as const,
                assigneeId: scope.assigneeId ?? null, secondControllerId: scope.secondControllerId ?? null,
                directorateId: control.directorateId,
            });
        }
        const result = await tx.controlTest.createMany({ data: rows, skipDuplicates: true });
        return result.count;
    }

    /**
     * Gerçek eşzamanlı isteklerde testNo sıra numarası hesabı iki transaction
     * arasında aynı "son değeri" görebilir (her ikisi de henüz commit etmemişken) —
     * bu durumda testNo @unique kısıtı P2002 fırlatır ve TÜM transaction (kapsam +
     * task) temiz şekilde rollback olur (yarım kayıt kalmaz). Burada kısa bir
     * retry ile isteğin kullanıcıya hatasız dönmesi sağlanır; (scopeId,periodKey)
     * kısıtı zaten mükerrer TASK oluşumuna karşı asıl güvence.
     */
    private async withUniqueRetry<T>(fn: () => Promise<T>, attempts = 3): Promise<T> {
        for (let i = 0; i < attempts; i++) {
            try {
                return await fn();
            } catch (e: any) {
                if (e?.code === 'P2002' && i < attempts - 1) continue;
                throw e;
            }
        }
        throw new Error('unreachable');
    }

    /**
     * Bir mutasyon adımını ya VERİLEN dış transaction içinde (Yıllık Plan'ın
     * çoklu-kontrol "Planı Uygula" akışı gibi — birden fazla addScope/
     * removeScope/changePeriodicity çağrısını TEK atomik birime toplamak için)
     * ya da hiç verilmemişse kendi transaction'ını açarak çalıştırır. Dış tx
     * verildiğinde retry uygulanmaz — bütünün retry/rollback sorumluluğu
     * çağırana (dış transaction sahibine) aittir.
     */
    private async runInTx<T>(tx: any | undefined, fn: (tx: any) => Promise<T>): Promise<T> {
        if (tx) return fn(tx);
        return this.withUniqueRetry(() => this.prisma.$transaction(fn));
    }

    /** Public — annual-plan.service.ts'in previewApply'ı da AYNI geçmiş-dönem
     * filtresini kullanmalı, aksi halde önizleme (addScope'un asıl üreteceğinden
     * fazla) yanlış task sayısı gösterir (madde 8/16: önizleme gerçek farkı yansıtmalı). */
    computePeriodsForScope(
        frequency: string, year: number, selectedMonths: string[], controlDate: Date | null,
        includePastPeriods: boolean, referenceMonth?: number | null,
    ): ScopePeriod[] {
        let periods = computeScopePeriods(frequency as any, year, { selectedMonths, controlDate, referenceMonth });
        const currentYear = new Date().getFullYear();
        if (year === currentYear && !includePastPeriods) {
            const now = new Date();
            periods = periods.filter(p => p.end >= now);
        }
        return periods;
    }

    /**
     * Kontrolcü atama doğrulaması — transaction İÇİNDE çalışır (stale/pasif
     * kullanıcı okuma riski yok). Aynı kişi iki alana atanamaz; pasif kullanıcı
     * yeni atama alamaz; ikinci kontrolcü için approveTest'teki asgari yetki
     * tabanına eşdeğer bir kontrol uygulanır (controls.service.ts::approveTest).
     */
    /** Public — annual-plan.service.ts taslak satırı kaydederken de aynı doğrulamayı kullanır. */
    async validateAssignment(tx: any, assigneeId?: string | null, secondControllerId?: string | null) {
        if (assigneeId && secondControllerId && assigneeId === secondControllerId) {
            throw new BadRequestException('Aynı kişi hem atanan kontrolcü hem ikinci kontrolcü olamaz.');
        }
        for (const [role, id] of [['Atanan Kontrolcü', assigneeId], ['İkinci Kontrolcü', secondControllerId]] as const) {
            if (!id) continue;
            const user = await tx.user.findUnique({ where: { id }, select: { isActive: true, role: { select: { permissions: true } } } });
            if (!user) throw new BadRequestException(`Geçersiz kullanıcı (${role})`);
            if (!user.isActive) throw new BadRequestException(`Pasif kullanıcı yeni atama alamaz (${role})`);
            if (role === 'İkinci Kontrolcü') {
                const perms: string[] = Array.isArray(user.role?.permissions) ? user.role.permissions : [];
                const eligible = perms.some(p => p === '*' || p === 'control:*' || p === 'control:test' || p.startsWith('control:'));
                if (!eligible) {
                    throw new BadRequestException('Seçilen kullanıcı ikinci kontrolcü onayı verebilecek yetkiye sahip değil.');
                }
            }
        }
    }

    // ─── Kapsama alma (tek/çoklu yıl) — kapsam + task üretimi tek transaction ─
    // `externalTx` verilirse (Yıllık Plan apply akışı) kendi transaction'ını
    // AÇMAZ, verilen tx'i kullanır — böylece birden fazla kontrolün kapsam
    // değişikliği tek atomik birimde toplanabilir.
    async addScope(controlId: string, dto: AddScopeDto, userId: string, externalTx?: any) {
        const db: any = externalTx ?? this.prisma;
        const control = await db.control.findUnique({ where: { id: controlId } });
        if (!control) throw new NotFoundException(`Kontrol ${controlId} bulunamadı`);
        if (control.status !== 'ACTIVE') {
            throw new BadRequestException('Pasif kontrol yeni bir yıl kapsamına alınamaz. Önce kontrolü aktifleştirin.');
        }

        if (dto.assigneeId !== undefined || dto.secondControllerId !== undefined) {
            await this.validateAssignment(db, dto.assigneeId || null, dto.secondControllerId || null);
        }

        const results: any[] = [];

        for (const year of dto.years) {
            const frequency = dto.frequency || control.frequency;
            const referenceMonth = dto.referenceMonth ?? null;
            // Periyodik sıklıklar (QUARTERLY/SEMI_ANNUAL/ANNUAL) için referenceMonth
            // varsa selectedMonths İSTEMCİDEN GÜVENİLMEZ — backend kendi hesaplar
            // (madde 21: istemciden gelen keyfi ay listesine güvenme).
            const selectedMonths = referenceMonth != null && ['QUARTERLY', 'SEMI_ANNUAL', 'ANNUAL'].includes(frequency)
                ? monthNumbersToLabels(computeMonthGroup(frequency as any, referenceMonth))
                : (dto.selectedMonths ?? control.selectedMonths);
            const controlDate = dto.controlDate ? new Date(dto.controlDate) : control.controlDate;
            const includePastPeriods = dto.includePastPeriods ?? false;
            const periods = this.computePeriodsForScope(frequency, year, selectedMonths, controlDate, includePastPeriods, referenceMonth);

            if (dto.dryRun) {
                const existingScope = await db.controlYearScope.findUnique({ where: { controlId_year: { controlId, year } } });
                let existingKeys = new Set<string>();
                if (existingScope) {
                    const existingTasks = await db.controlTest.findMany({ where: { scopeId: existingScope.id }, select: { periodKey: true } });
                    existingKeys = new Set(existingTasks.map((t: { periodKey: string | null }) => t.periodKey as string));
                }
                const newPeriods = periods.filter(p => !existingKeys.has(p.periodKey));
                results.push({
                    year,
                    alreadyInScope: !!existingScope && existingScope.status === 'ACTIVE',
                    periods: periods.map(p => ({ periodKey: p.periodKey, periodLabel: p.periodLabel, targetDate: p.targetDate })),
                    newTaskCount: newPeriods.length,
                    totalPeriodCount: periods.length,
                });
                continue;
            }

            const outcome = await this.runInTx(externalTx, async (tx) => {
                let scope = await tx.controlYearScope.findUnique({ where: { controlId_year: { controlId, year } } });
                let action: string;
                let oldValue: any = null;

                const assigneeId = dto.assigneeId !== undefined ? (dto.assigneeId || null) : undefined;
                const secondControllerId = dto.secondControllerId !== undefined ? (dto.secondControllerId || null) : undefined;

                if (!scope) {
                    scope = await tx.controlYearScope.create({
                        data: {
                            controlId, year, frequency, referenceMonth, selectedMonths, controlDate, addedById: userId,
                            assigneeId: assigneeId ?? null, secondControllerId: secondControllerId ?? null,
                        },
                    });
                    action = 'SCOPE_ADD';
                } else if (scope.status === 'REMOVED') {
                    oldValue = scope;
                    scope = await tx.controlYearScope.update({
                        where: { id: scope.id },
                        data: {
                            status: 'ACTIVE', addedById: userId, addedAt: new Date(), removedById: null, removedAt: null, removalReason: null,
                            ...(assigneeId !== undefined ? { assigneeId } : {}),
                            ...(secondControllerId !== undefined ? { secondControllerId } : {}),
                        },
                    });
                    action = 'SCOPE_REACTIVATE';
                } else {
                    action = 'SCOPE_ADD_NOOP';
                }

                await tx.auditLog.create({
                    data: { userId, action, entityType: 'ControlYearScope', entityId: scope.id, oldValue, newValue: scope },
                });

                const created = await this.generateTasksForPeriods(tx, scope, control, periods);
                return { scope, created, action };
            });

            results.push({ year, scopeId: outcome.scope.id, action: outcome.action, tasksCreated: outcome.created });
        }

        return { results };
    }

    async reactivateScope(controlId: string, year: number, userId: string, externalTx?: any) {
        return this.addScope(controlId, { years: [year] } as AddScopeDto, userId, externalTx);
    }

    // ─── Toplu kapsama alma ────────────────────────────────────────────────────
    async bulkAddScope(dto: BulkAddScopeDto, userId: string) {
        const perControlDto: AddScopeDto = {
            years: [dto.year], frequency: dto.frequency, selectedMonths: dto.selectedMonths,
            includePastPeriods: dto.includePastPeriods, dryRun: dto.dryRun,
        };
        const results: any[] = [];
        for (const controlId of dto.controlIds) {
            try {
                const r = await this.addScope(controlId, perControlDto, userId);
                results.push({ controlId, ...r.results[0] });
            } catch (e: any) {
                results.push({ controlId, error: e?.message || 'Bilinmeyen hata' });
            }
        }
        return { results };
    }

    // ─── Önceki yıldan kopyalama (yalnızca kapsam/planlama, sonuç/kanıt yok) ──
    async copyScope(dto: CopyScopeDto, userId: string) {
        const where: any = { year: dto.fromYear, status: 'ACTIVE' };
        if (dto.controlIds?.length) where.controlId = { in: dto.controlIds };
        const sourceScopes = await this.prisma.controlYearScope.findMany({ where, include: { control: true } });

        if (dto.dryRun) {
            const targets = await this.prisma.controlYearScope.findMany({
                where: { year: dto.toYear, controlId: { in: sourceScopes.map(s => s.controlId) } },
                select: { controlId: true },
            });
            const existing = new Set(targets.map(t => t.controlId));
            return {
                total: sourceScopes.length,
                toCopy: sourceScopes.filter(s => !existing.has(s.controlId)).length,
                alreadyExists: sourceScopes.filter(s => existing.has(s.controlId)).length,
            };
        }

        let copied = 0, skipped = 0;
        for (const src of sourceScopes) {
            if (src.control.status !== 'ACTIVE') { skipped++; continue; }
            const existing = await this.prisma.controlYearScope.findUnique({ where: { controlId_year: { controlId: src.controlId, year: dto.toYear } } });
            if (existing) { skipped++; continue; }

            const periods = this.computePeriodsForScope(src.frequency, dto.toYear, src.selectedMonths, src.controlDate, false);

            await this.prisma.$transaction(async (tx) => {
                const scope = await tx.controlYearScope.create({
                    data: {
                        controlId: src.controlId, year: dto.toYear, frequency: src.frequency,
                        selectedMonths: src.selectedMonths, controlDate: src.controlDate,
                        addedById: userId, copiedFromYear: dto.fromYear,
                    },
                });
                await tx.auditLog.create({
                    data: { userId, action: 'SCOPE_COPY', entityType: 'ControlYearScope', entityId: scope.id, newValue: { ...scope, copiedFromScopeId: src.id } },
                });
                await this.generateTasksForPeriods(tx, scope, src.control, periods);
            });
            copied++;
        }

        return { total: sourceScopes.length, copied, skipped };
    }

    /** `removeScope`'un ön-kontrolü — devam eden (DEVAM_EDIYOR) tasklar için
     * karar verilmemişse listeler. Yıllık Plan apply akışı, kapsamdan çıkarma
     * gerektiren HER kontrol için gerçek kaldırmadan ÖNCE bunu çağırıp tüm
     * planı tek seferde, atomik biçimde bloke/serbest bırakır. */
    async getOngoingTasksRequiringDecision(scopeId: string, decisions: { taskId: string; action: string }[] = [], db: any = this.prisma) {
        const ongoing = await db.controlTest.findMany({
            where: { scopeId, status: 'DEVAM_EDIYOR' },
            select: { id: true, testNo: true, periodLabel: true, assigneeId: true, plannedDate: true },
        });
        const decidedIds = new Set(decisions.map(d => d.taskId));
        return ongoing.filter((t: { id: string }) => !decidedIds.has(t.id));
    }

    // ─── Kapsamdan çıkarma (gerekçe zorunlu, devam eden tasklar için karar) ───
    async removeScope(controlId: string, year: number, dto: RemoveScopeDto, userId: string, externalTx?: any) {
        const db: any = externalTx ?? this.prisma;
        const scope = await db.controlYearScope.findUnique({ where: { controlId_year: { controlId, year } } });
        if (!scope) throw new NotFoundException('Bu kontrol için belirtilen yılda kapsam kaydı bulunamadı');
        if (scope.status === 'REMOVED') throw new BadRequestException('Bu kapsam zaten kaldırılmış');

        const missingDecisions = await this.getOngoingTasksRequiringDecision(scope.id, dto.decisions || [], db);
        if (missingDecisions.length > 0) {
            return {
                requiresDecision: true,
                ongoingTasks: missingDecisions,
                message: 'Devam eden tasklar için devam/iptal kararı verilmeden kapsam kaldırılamaz.',
            };
        }

        const updated = await this.runInTx(externalTx, async (tx) => {
            const oldValue = scope;
            const newScope = await tx.controlYearScope.update({
                where: { id: scope.id },
                data: { status: 'REMOVED', removedById: userId, removedAt: new Date(), removalReason: dto.reason },
            });

            await tx.controlTest.updateMany({
                where: { scopeId: scope.id, status: 'BEKLIYOR' },
                data: { status: 'KAPSAM_DISI', outOfScopeAt: new Date(), outOfScopeById: userId, outOfScopeReason: dto.reason },
            });

            const toCancel = (dto.decisions || []).filter(d => d.action === 'CANCEL').map(d => d.taskId);
            if (toCancel.length > 0) {
                await tx.controlTest.updateMany({
                    where: { id: { in: toCancel }, scopeId: scope.id, status: 'DEVAM_EDIYOR' },
                    data: { status: 'KAPSAM_DISI', outOfScopeAt: new Date(), outOfScopeById: userId, outOfScopeReason: dto.reason },
                });
            }

            await tx.auditLog.create({
                data: {
                    userId, action: 'SCOPE_REMOVE', entityType: 'ControlYearScope', entityId: scope.id,
                    oldValue, newValue: { ...newScope, decisions: JSON.parse(JSON.stringify(dto.decisions || [])) },
                },
            });

            return newScope;
        });

        return { requiresDecision: false, scope: updated };
    }

    // ─── Periyodiklik/takvim/atama değişikliği (yalnızca BEKLIYOR tasklar
    // serbestçe etkilenir; devam eden/tamamlanmış tasklar korunur veya açık
    // karar ister) — assignment-only değişiklik de bu metottan geçer (madde 6).
    async changePeriodicity(controlId: string, year: number, dto: ChangePeriodicityDto, userId: string, externalTx?: any) {
        const db: any = externalTx ?? this.prisma;
        const scope = await db.controlYearScope.findUnique({ where: { controlId_year: { controlId, year } }, include: { control: true } });
        if (!scope) throw new NotFoundException('Bu kontrol için belirtilen yılda kapsam kaydı bulunamadı');
        if (scope.status !== 'ACTIVE') throw new BadRequestException('Yalnızca aktif kapsamların periyodikliği değiştirilebilir');

        const newFrequency = dto.frequency || scope.frequency;
        const newReferenceMonth = dto.referenceMonth !== undefined ? dto.referenceMonth : scope.referenceMonth;
        const newSelectedMonths = newReferenceMonth != null && ['QUARTERLY', 'SEMI_ANNUAL', 'ANNUAL'].includes(newFrequency)
            ? monthNumbersToLabels(computeMonthGroup(newFrequency as any, newReferenceMonth))
            : (dto.selectedMonths ?? scope.selectedMonths);
        const newPeriods = computeScopePeriods(newFrequency as any, year, { selectedMonths: newSelectedMonths, controlDate: scope.controlDate, referenceMonth: newReferenceMonth });
        const newKeys = new Set(newPeriods.map(p => p.periodKey));

        const newAssigneeId = dto.assigneeId !== undefined ? (dto.assigneeId || null) : scope.assigneeId;
        const newSecondControllerId = dto.secondControllerId !== undefined ? (dto.secondControllerId || null) : scope.secondControllerId;
        const assignmentChanged = newAssigneeId !== scope.assigneeId || newSecondControllerId !== scope.secondControllerId;

        const existingTasks: any[] = await db.controlTest.findMany({ where: { scopeId: scope.id } });
        const toCancel = existingTasks.filter((t: any) => t.status === 'BEKLIYOR' && t.periodKey && !newKeys.has(t.periodKey));
        const existingKeys = new Set(existingTasks.map((t: any) => t.periodKey));
        const toCreate = newPeriods.filter(p => !existingKeys.has(p.periodKey));
        const protectedTasks = existingTasks.filter((t: any) => t.status !== 'BEKLIYOR' && t.periodKey && !newKeys.has(t.periodKey));

        // Atama değişikliği: yalnızca isAutoGenerated task'lar etkilenir (manuel
        // override'lar korunur). BEKLIYOR → serbestçe güncellenir. DEVAM_EDIYOR/
        // TAMAMLANDI/GERI_GONDERILDI → açık karar gerekir (removeScope'un
        // getOngoingTasksRequiringDecision deseniyle aynı UX). ONAYLANDI/IPTAL/
        // KAPSAM_DISI → asla dokunulmaz.
        const liveAutoTasks = existingTasks.filter((t: any) => t.isAutoGenerated);
        const assignmentFreelyUpdatable = assignmentChanged
            ? liveAutoTasks.filter((t: any) => LIVE_TASK_STATUSES_FREE.includes(t.status))
            : [];
        const assignmentNeedsDecision = assignmentChanged
            ? liveAutoTasks.filter((t: any) =>
                LIVE_TASK_STATUSES_DECISION.includes(t.status) &&
                (t.assigneeId !== newAssigneeId || t.secondControllerId !== newSecondControllerId))
            : [];
        const decidedIds = new Set((dto.assignmentDecisions || []).filter(d => d.action === 'REASSIGN').map(d => d.taskId));
        const undecidedAssignmentTasks = assignmentNeedsDecision.filter((t: any) => {
            const decision = (dto.assignmentDecisions || []).find(d => d.taskId === t.id);
            return !decision; // ne REASSIGN ne KEEP verilmiş — karar bekliyor
        });

        if (dto.dryRun) {
            return {
                currentFrequency: scope.frequency, newFrequency,
                toCancelCount: toCancel.length, toCreateCount: toCreate.length,
                protectedCount: protectedTasks.length,
                assignmentChanged,
                assignmentFreelyUpdatableCount: assignmentFreelyUpdatable.length,
                assignmentNeedsDecisionCount: assignmentNeedsDecision.length,
            };
        }

        if (assignmentChanged) {
            await this.validateAssignment(db, newAssigneeId, newSecondControllerId);
            if (undecidedAssignmentTasks.length > 0) {
                return {
                    requiresAssignmentDecision: true,
                    tasks: undecidedAssignmentTasks.map((t: any) => ({
                        id: t.id, testNo: t.testNo, periodLabel: t.periodLabel, status: t.status,
                        currentAssigneeId: t.assigneeId, currentSecondControllerId: t.secondControllerId,
                    })),
                    message: 'Devam eden/onay bekleyen tasklar için atama değişikliği kararı verilmeden uygulanamaz.',
                };
            }
        }

        const result = await this.runInTx(externalTx, async (tx) => {
            const oldValue = {
                frequency: scope.frequency, selectedMonths: scope.selectedMonths, referenceMonth: scope.referenceMonth,
                assigneeId: scope.assigneeId, secondControllerId: scope.secondControllerId,
            };
            const updatedScope = await tx.controlYearScope.update({
                where: { id: scope.id },
                data: {
                    frequency: newFrequency, selectedMonths: newSelectedMonths, referenceMonth: newReferenceMonth,
                    assigneeId: newAssigneeId, secondControllerId: newSecondControllerId,
                },
            });

            if (toCancel.length > 0) {
                await tx.controlTest.updateMany({
                    where: { id: { in: toCancel.map((t: any) => t.id) } },
                    data: {
                        status: 'KAPSAM_DISI', outOfScopeAt: new Date(), outOfScopeById: userId,
                        outOfScopeReason: `Periyodiklik değişikliği: ${dto.reason}`,
                    },
                });
            }

            if (assignmentChanged) {
                if (assignmentFreelyUpdatable.length > 0) {
                    await tx.controlTest.updateMany({
                        where: { id: { in: assignmentFreelyUpdatable.map((t: any) => t.id) } },
                        data: { assigneeId: newAssigneeId, secondControllerId: newSecondControllerId },
                    });
                }
                const toReassign = assignmentNeedsDecision.filter((t: any) => decidedIds.has(t.id));
                if (toReassign.length > 0) {
                    await tx.controlTest.updateMany({
                        where: { id: { in: toReassign.map((t: any) => t.id) } },
                        data: { assigneeId: newAssigneeId, secondControllerId: newSecondControllerId },
                    });
                }
                await tx.auditLog.create({
                    data: {
                        userId, action: 'SCOPE_ASSIGNMENT_CHANGE', entityType: 'ControlYearScope', entityId: scope.id,
                        oldValue: { assigneeId: scope.assigneeId, secondControllerId: scope.secondControllerId },
                        newValue: { assigneeId: newAssigneeId, secondControllerId: newSecondControllerId, reason: dto.reason },
                    },
                });
            }

            await tx.auditLog.create({
                data: {
                    userId, action: 'SCOPE_PERIODICITY_CHANGE', entityType: 'ControlYearScope', entityId: scope.id,
                    oldValue, newValue: { frequency: newFrequency, selectedMonths: newSelectedMonths, referenceMonth: newReferenceMonth, reason: dto.reason },
                },
            });

            const created = await this.generateTasksForPeriods(tx, updatedScope, scope.control, toCreate);
            return { scope: updatedScope, cancelled: toCancel.length, created, requiresAssignmentDecision: false };
        });

        return result;
    }

    // ─── Task yeniden etkinleştirme (açık işlem, otomatik değil) ─────────────
    async reactivateTask(taskId: string, userId: string) {
        const task = await this.prisma.controlTest.findUnique({ where: { id: taskId } });
        if (!task) throw new NotFoundException(`Task ${taskId} bulunamadı`);
        if (task.status !== 'KAPSAM_DISI') {
            throw new BadRequestException('Yalnızca kapsam dışı bırakılmış tasklar yeniden etkinleştirilebilir');
        }

        const updated = await this.prisma.controlTest.update({
            where: { id: taskId },
            data: { status: 'BEKLIYOR', outOfScopeAt: null, outOfScopeById: null, outOfScopeReason: null },
        });

        await this.prisma.auditLog.create({
            data: { userId, action: 'REACTIVATE_TASK', entityType: 'ControlTest', entityId: taskId, oldValue: task, newValue: updated },
        });

        return updated;
    }

    // ─── Kapsam geçmişi ────────────────────────────────────────────────────────
    async getScopeHistory(controlId: string) {
        const scopes = await this.prisma.controlYearScope.findMany({ where: { controlId }, select: { id: true, year: true } });
        const scopeIds = scopes.map(s => s.id);
        if (scopeIds.length === 0) return { data: [] };

        const logs = await this.prisma.auditLog.findMany({
            where: { entityType: 'ControlYearScope', entityId: { in: scopeIds } },
            include: { user: { select: { firstName: true, lastName: true, email: true } } },
            orderBy: { createdAt: 'desc' },
        });

        const yearByScope = new Map(scopes.map(s => [s.id, s.year]));
        return { data: logs.map(l => ({ ...l, year: yearByScope.get(l.entityId) })) };
    }
}
