'use client';

import { useState, useEffect, useMemo, useCallback, Suspense } from 'react';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import api from '@/lib/api';
import {
    PageHeader, PageShell, StatusBadge, Button, DataTable, Modal,
    KpiCard, KpiGrid, AdvancedFilterPanel, ActiveFilterChips, SavedViewMenu,
} from '@/components/ui';
import type { ColumnDef, ActiveFilterChip, AdvancedFilterField } from '@/components/ui';
import { useToast } from '@/components/ui/Toast';
import { CreateFindingModal } from '@/components/modals/CreateFindingModal';
import { FileUpload, type AttachmentMeta } from '@/components/ui';
import { useAuth } from '@/components/auth';

// ─── Types ────────────────────────────────────────────────────────────────────

type BV = 'critical' | 'high' | 'medium' | 'low' | 'info' | 'success' | 'warning' | 'neutral' | 'primary';

interface ControlTest {
    id: string;
    testNo: string;
    controlId: string;
    plannedDate: string;
    completedAt?: string | null;
    status: string;
    findingStatus?: string | null;
    resultText?: string | null;
    evidenceSummary?: string | null;
    assigneeId?: string | null;
    isAutoGenerated: boolean;
    summary?: string | null;
    control: {
        id: string;
        controlId: string;
        name: string;
        type: string;
        frequency: string;
        gmy?: string | null;
    };
    directorate?: { id: string; name: string; code?: string | null } | null;
    findings?: { id: string; findingId: string; severity: string; resolutionStatus: string }[];
    attachments?: { id: string; fileName: string; originalName: string; mimeType: string; sizeBytes: number }[];
}

// ─── Config ───────────────────────────────────────────────────────────────────

const statusConfig: Record<string, { label: string; variant: BV }> = {
    BEKLIYOR:         { label: 'Bekliyor',           variant: 'neutral' },
    DEVAM_EDIYOR:     { label: 'Devam Ediyor',       variant: 'warning' },
    TAMAMLANDI:       { label: 'Onay Bekliyor',      variant: 'info' },
    GERI_GONDERILDI:  { label: 'Geri Gönderildi',    variant: 'critical' },
    ONAYLANDI:        { label: 'Onaylandı',          variant: 'success' },
    IPTAL:            { label: 'İptal Edildi',       variant: 'neutral' },
};

const findingStatusConfig: Record<string, { label: string; variant: BV }> = {
    BULGUSU_YOK: { label: 'Bulgu Yok', variant: 'success' },
    BULGUSU_VAR: { label: 'Bulgu Var', variant: 'critical' },
};

const severityConfig: Record<string, { label: string; variant: BV }> = {
    CRITICAL: { label: 'KZ', variant: 'critical' },
    HIGH:     { label: 'KD', variant: 'high' },
    MEDIUM:   { label: 'ÖK', variant: 'medium' },
    LOW:      { label: 'Düşük', variant: 'low' },
};

const fmt = (d?: string | null) => {
    if (!d) return '—';
    const dt = new Date(d);
    return isNaN(dt.getTime()) ? '—' : dt.toLocaleDateString('tr-TR');
};

const MONTHS_TR = ['Ocak', 'Şubat', 'Mart', 'Nisan', 'Mayıs', 'Haziran', 'Temmuz', 'Ağustos', 'Eylül', 'Ekim', 'Kasım', 'Aralık'];
const MONTHS_SHORT = ['Oca', 'Şub', 'Mar', 'Nis', 'May', 'Haz', 'Tem', 'Ağu', 'Eyl', 'Eki', 'Kas', 'Ara'];

/** Gecikmiş testi belirleyen tek predicate — KPI ve filtre aynı kuralı kullanır */
const isOverdue = (t: ControlTest) =>
    ['BEKLIYOR', 'DEVAM_EDIYOR'].includes(t.status) && new Date(t.plannedDate) < new Date();

// ─── Inline SVG Icons ─────────────────────────────────────────────────────────

const icn = 'w-3.5 h-3.5';

const IconCalendar = ({ className = icn }: { className?: string }) => (
    <svg className={className} fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" /></svg>
);
const IconPin = ({ className = icn }: { className?: string }) => (
    <svg className={className} fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" /><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" /></svg>
);
const IconUser = ({ className = icn }: { className?: string }) => (
    <svg className={className} fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" /></svg>
);
const IconPlay = ({ className = icn }: { className?: string }) => (
    <svg className={className} fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M14.752 11.168l-3.197-2.132A1 1 0 0010 9.87v4.263a1 1 0 001.555.832l3.197-2.132a1 1 0 000-1.664z" /><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
);
const IconCheck = ({ className = icn }: { className?: string }) => (
    <svg className={className} fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" /></svg>
);
const IconCheckCircle = ({ className = icn }: { className?: string }) => (
    <svg className={className} fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
);
const IconReturn = ({ className = icn }: { className?: string }) => (
    <svg className={className} fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 10h10a5 5 0 015 5v1M3 10l5-5m-5 5l5 5" /></svg>
);
const IconBan = ({ className = icn }: { className?: string }) => (
    <svg className={className} fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M18.364 18.364A9 9 0 005.636 5.636m12.728 12.728A9 9 0 015.636 5.636m12.728 12.728L5.636 5.636" /></svg>
);
const IconWarning = ({ className = icn }: { className?: string }) => (
    <svg className={className} fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" /></svg>
);
const IconLink = ({ className = icn }: { className?: string }) => (
    <svg className={className} fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13.828 10.172a4 4 0 010 5.656l-4 4a4 4 0 01-5.656-5.656l1.102-1.101m9.554-9.554l1.102-1.101a4 4 0 015.656 5.656l-4 4a4 4 0 01-5.656 0" /></svg>
);
const IconPlus = ({ className = icn }: { className?: string }) => (
    <svg className={className} fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" /></svg>
);

// ─── Reason Modal (prompt/confirm yerine) ─────────────────────────────────────

function ReasonModal({
    open, title, description, confirmLabel, reasonRequired, saving, onConfirm, onClose,
}: {
    open: boolean;
    title: string;
    description?: string;
    confirmLabel: string;
    /** true ise gerekçe boşken Onayla disabled */
    reasonRequired: boolean;
    saving: boolean;
    onConfirm: (reason: string) => void;
    onClose: () => void;
}) {
    const [reason, setReason] = useState('');
    useEffect(() => { if (open) setReason(''); }, [open]);

    return (
        <Modal
            open={open}
            onClose={onClose}
            title={title}
            description={description}
            size="sm"
            footer={
                <>
                    <Button variant="outline" onClick={onClose} disabled={saving}>İptal</Button>
                    <Button
                        variant="primary"
                        onClick={() => onConfirm(reason)}
                        loading={saving}
                        disabled={saving || (reasonRequired && !reason.trim())}
                    >
                        {confirmLabel}
                    </Button>
                </>
            }
        >
            <label className="block text-xs font-medium text-slate-600 mb-1.5">
                Gerekçe {reasonRequired ? <span className="text-red-500">*</span> : <span className="text-slate-400">(opsiyonel)</span>}
            </label>
            <textarea
                autoFocus
                value={reason}
                onChange={e => setReason(e.target.value)}
                rows={3}
                placeholder="Gerekçenizi yazın..."
                className="w-full border border-slate-200 rounded-lg px-3 py-2 text-sm text-slate-700 resize-none
                           focus:outline-none focus:border-blue-400 focus:ring-2 focus:ring-blue-100 transition-all duration-150"
            />
        </Modal>
    );
}

// ─── WorkspacePanel ──────────────────────────────────────────────────────────

function WorkspacePanel({
    test, users, onRefresh, onClose,
}: {
    test: ControlTest;
    users: { id: string; firstName: string; lastName: string; email: string }[];
    onRefresh: () => void;
    onClose: () => void;
}) {
    const { success, error: showError } = useToast();
    const [saving, setSaving] = useState(false);
    const [findingModalOpen, setFindingModalOpen] = useState(false);
    const [reasonModal, setReasonModal] = useState<null | 'return' | 'cancel'>(null);
    const hasFindings = (test.findings?.length ?? 0) > 0;

    // Madde 6: devam eden açık bulguyu referans alarak ilerletme
    const [openFindings, setOpenFindings] = useState<{ id: string; findingId: string; summary?: string | null }[]>([]);
    const [referencedFindingId, setReferencedFindingId] = useState('');
    const [referenceReason, setReferenceReason] = useState('');
    const [form, setForm] = useState({
        resultText: test.resultText || '',
        evidenceSummary: test.evidenceSummary || '',
        // Bağlı açık bulgu varsa BULGUSU_VAR ile başla — test.findingStatus yalnızca test
        // tamamlanınca dolar, o ana kadar tek doğru sinyal bağlı bulgu kaydının varlığıdır.
        findingStatus: test.findingStatus || (hasFindings ? 'BULGUSU_VAR' : 'BULGUSU_YOK'),
    });

    // Madde 5 bug fix: kullanıcı "Bulgu Var" seçip yeni bulgu ekledikten sonra panel
    // yeniden açıldığında (test/hasFindings değiştiğinde) seçim "Bulgu Yok"a düşmemeli —
    // bağlı bulgu varsa seçim her zaman BULGUSU_VAR'a senkronize edilir.
    useEffect(() => {
        if (hasFindings) {
            setForm(p => (p.findingStatus === 'BULGUSU_VAR' ? p : { ...p, findingStatus: 'BULGUSU_VAR' }));
        }
    }, [hasFindings, test.id]);

    // Bu kontrole ait, henüz kapanmamış diğer bulguları getir (referans seçeneği için)
    useEffect(() => {
        if (hasFindings) return;
        api.getFindings({ controlId: test.control.id, limit: 100 })
            .then((res: any) => {
                const list = Array.isArray(res) ? res : (res?.data || []);
                setOpenFindings(list.filter((f: any) => f.status !== 'CLOSED'));
            })
            .catch(() => setOpenFindings([]));
    }, [test.control.id, hasFindings]);

    const canStart    = test.status === 'BEKLIYOR';
    const canComplete = test.status === 'DEVAM_EDIYOR' || test.status === 'GERI_GONDERILDI';
    const canApprove  = test.status === 'TAMAMLANDI';
    const canReturn   = test.status === 'TAMAMLANDI';
    const isDone      = test.status === 'ONAYLANDI';
    const isCancelled = test.status === 'IPTAL';
    // BULGUSU_VAR seçildiyse bulgu eklenene kadar "Testi Tamamla" disabled
    const needsFindingFirst = form.findingStatus === 'BULGUSU_VAR' && !hasFindings;
    const completeBlockedReason = needsFindingFirst
        ? 'Önce "Bulgu Kaydı Oluştur" ile bir bulgu kaydı ekleyin.'
        : null;

    const handleStart = async () => {
        setSaving(true);
        try {
            await api.startControlTest(test.id);
            success('Başlatıldı', 'Test Devam Ediyor statüsüne alındı.');
            onRefresh();
        } catch { showError('Hata', 'Test başlatılamadı.'); }
        finally { setSaving(false); }
    };

    const handleComplete = async () => {
        setSaving(true);
        try {
            await api.completeControlTest(test.id, {
                findingStatus: form.findingStatus,
                resultText: form.resultText,
                evidenceSummary: form.evidenceSummary,
            });
            success('Tamamlandı', 'Test sonucu kaydedildi, 2. kontrolcü onayına gönderildi.');
            onRefresh();
        } catch (err: any) { showError('Hata', err.message || 'Test tamamlanamadı.'); }
        finally { setSaving(false); }
    };

    const handleReference = async () => {
        if (!referencedFindingId) return;
        setSaving(true);
        try {
            await api.completeControlTest(test.id, {
                referencedFindingId,
                referenceReason,
            });
            success('İlerletildi', 'Test, referans verilen açık bulgu ile 2. kontrolcü onayına gönderildi.');
            onRefresh();
        } catch (err: any) { showError('Hata', err.message || 'Referans ile ilerletilemedi.'); }
        finally { setSaving(false); }
    };

    const handleApprove = async () => {
        setSaving(true);
        try {
            await api.approveControlTest(test.id);
            success('Onaylandı', 'Test onaylandı.');
            onRefresh();
        } catch { showError('Hata', 'Test onaylanamadı.'); }
        finally { setSaving(false); }
    };

    // prompt() yerine ReasonModal — geri gönderme gerekçesi zorunlu
    const handleReturnConfirm = async (reason: string) => {
        if (!reason.trim()) return;
        setSaving(true);
        try {
            await api.returnControlTest(test.id, reason);
            success('Geri Gönderildi', 'Test testi yapan kullanıcıya düzeltme için geri gönderildi.');
            setReasonModal(null);
            onRefresh();
        } catch { showError('Hata', 'Geri gönderilemedi.'); }
        finally { setSaving(false); }
    };

    const { user } = useAuth();
    const isSystemAdmin = user?.role?.name === 'SYSTEM_ADMIN';

    // prompt()+confirm() yerine ReasonModal — iptal gerekçesi opsiyonel, modal onayı confirm yerine geçer
    const handleCancelFinalConfirm = async (reason: string) => {
        setSaving(true);
        try {
            await api.cancelControlTest(test.id, reason);
            success('İptal Edildi', 'Final onaylı test iptal edildi.');
            setReasonModal(null);
            onRefresh();
        } catch { showError('Hata', 'Test iptal edilemedi.'); }
        finally { setSaving(false); }
    };

    const stCfg = statusConfig[test.status] || { label: test.status, variant: 'neutral' as BV };

    return (
        <div className="h-full flex flex-col bg-white">
            {/* Header */}
            <div className="flex items-center justify-between px-5 py-4 border-b border-slate-200 bg-slate-50">
                <div className="min-w-0">
                    <div className="flex items-center gap-2 mb-1.5">
                        <span className="font-mono text-xs font-semibold text-slate-600 bg-slate-100 border border-slate-200 rounded px-2 py-0.5">{test.testNo}</span>
                        <StatusBadge variant={stCfg.variant}>{stCfg.label}</StatusBadge>
                        {test.findingStatus && (
                            <StatusBadge variant={findingStatusConfig[test.findingStatus]?.variant || 'neutral'}>
                                {findingStatusConfig[test.findingStatus]?.label || test.findingStatus}
                            </StatusBadge>
                        )}
                    </div>
                    <p className="text-sm font-semibold text-slate-800 max-w-xs truncate">{test.control.name}</p>
                    <div className="flex flex-wrap items-center gap-x-3 gap-y-1 text-xs text-slate-400 mt-1">
                        {test.directorate?.name && (
                            <span className="inline-flex items-center gap-1"><IconPin className="w-3 h-3" />{test.directorate.name}</span>
                        )}
                        <span className="inline-flex items-center gap-1"><IconCalendar className="w-3 h-3" />Plan: {fmt(test.plannedDate)}</span>
                        {test.completedAt && (
                            <span className="inline-flex items-center gap-1 text-emerald-600"><IconCheck className="w-3 h-3" />{fmt(test.completedAt)}</span>
                        )}
                    </div>
                </div>
                <button onClick={onClose} className="p-1.5 text-slate-400 hover:text-slate-700 rounded-lg hover:bg-slate-100 cursor-pointer" aria-label="Paneli kapat">
                    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" /></svg>
                </button>
            </div>

            <div className="flex-1 overflow-y-auto p-5 space-y-5">
                {/* Kontrol Bilgisi */}
                <div className="bg-slate-50 rounded-xl border border-slate-200 p-4 space-y-2 text-sm">
                    <div className="flex items-center justify-between">
                        <span className="text-sm font-semibold text-slate-700">Kontrol</span>
                        <Link href={`/controls/${test.control.id}`} className="text-blue-600 hover:underline text-xs font-mono">{test.control.controlId}</Link>
                    </div>
                    <p className="text-slate-800 font-medium">{test.control.name}</p>
                    {test.control.gmy && (
                        <p className="text-xs text-slate-500 inline-flex items-center gap-1.5"><IconUser className="w-3 h-3" />{test.control.gmy}</p>
                    )}
                </div>

                {/* Kanıt Ekleri — Bulgu Var/Yok'tan bağımsız her zaman görünür */}
                <div>
                    <FileUpload
                        label="Kanıt Ekleri"
                        disabled={isDone}
                        attachments={(test.attachments ?? []) as AttachmentMeta[]}
                        onUpload={async (meta) => {
                            try {
                                await api.addControlTestAttachment(test.id, meta);
                                success('Yüklendi', `${meta.originalName} eklendi.`);
                                onRefresh();
                            } catch { showError('Hata', 'Dosya eklenemedi.'); }
                        }}
                        onRemove={async (att) => {
                            if (!att.id) return;
                            try {
                                await api.removeControlTestAttachment(test.id, att.id);
                                onRefresh();
                            } catch { showError('Hata', 'Dosya silinemedi.'); }
                        }}
                    />
                </div>

                {/* İş Akışı Butonları */}
                {!isDone && !isCancelled && (
                    <div className="space-y-2">
                        <p className="text-sm font-semibold text-slate-700">İş Akışı</p>
                        {canStart && (
                            <Button variant="primary" size="sm" className="w-full" onClick={handleStart} disabled={saving} icon={<IconPlay />}>
                                Testi Başlat
                            </Button>
                        )}
                        {canComplete && (
                            <div>
                                <Button variant="primary" size="sm" className="w-full"
                                    onClick={handleComplete}
                                    disabled={saving || !form.findingStatus || needsFindingFirst}
                                    title={completeBlockedReason ?? undefined}
                                    icon={<IconCheck />}>
                                    Testi Tamamla ve Onaya Gönder
                                </Button>
                                {completeBlockedReason && (
                                    <p className="text-[11px] text-amber-600 mt-1.5">{completeBlockedReason}</p>
                                )}
                            </div>
                        )}
                        {canApprove && (
                            <Button variant="primary" size="sm" className="w-full" onClick={handleApprove} disabled={saving} icon={<IconCheckCircle />}>
                                Onayla (2. Kontrolcü)
                            </Button>
                        )}
                        {canReturn && (
                            <Button variant="secondary" size="sm" className="w-full" onClick={() => setReasonModal('return')} disabled={saving} icon={<IconReturn />}>
                                Geri Gönder
                            </Button>
                        )}
                    </div>
                )}

                {/* Final onaylı testi iptal — yalnızca SYSTEM_ADMIN */}
                {isDone && isSystemAdmin && (
                    <div className="space-y-2">
                        <p className="text-sm font-semibold text-slate-700">Yönetici İşlemleri</p>
                        <Button variant="secondary" size="sm" className="w-full text-red-600 border-red-200 hover:bg-red-50" onClick={() => setReasonModal('cancel')} disabled={saving} icon={<IconBan />}>
                            Final Onayı İptal Et
                        </Button>
                    </div>
                )}

                {/* Test Sonucu Formu */}
                {(canComplete || isDone) && (
                    <div className="space-y-4">
                        <div>
                            <p className="text-sm font-semibold text-slate-700 mb-2">Kontrol Sonucu</p>
                            <div className="grid grid-cols-2 gap-2">
                                {['BULGUSU_YOK', 'BULGUSU_VAR'].map(opt => (
                                    <button key={opt} type="button"
                                        disabled={isDone || (opt === 'BULGUSU_YOK' && hasFindings)}
                                        title={opt === 'BULGUSU_YOK' && hasFindings ? 'Bu teste bağlı bulgu kaydı var, sonuç Bulgu Yok olamaz.' : undefined}
                                        onClick={() => setForm(p => ({ ...p, findingStatus: opt }))}
                                        className={`p-3 rounded-xl border-2 text-sm font-semibold transition-all disabled:opacity-40 disabled:cursor-not-allowed ${
                                            form.findingStatus === opt
                                                ? opt === 'BULGUSU_YOK' ? 'border-emerald-400 bg-emerald-50 text-emerald-800' : 'border-red-400 bg-red-50 text-red-800'
                                                : 'border-slate-200 bg-white text-slate-600 hover:border-slate-300'
                                        } ${isDone ? 'opacity-60 cursor-default' : ''}`}
                                    >
                                        <span className="inline-flex items-center gap-1.5">
                                            {opt === 'BULGUSU_YOK' ? <IconCheck className="w-4 h-4" /> : <IconWarning className="w-4 h-4" />}
                                            {opt === 'BULGUSU_YOK' ? 'Bulgu Yok' : 'Bulgu Var'}
                                        </span>
                                    </button>
                                ))}
                            </div>
                        </div>

                        {form.findingStatus === 'BULGUSU_VAR' && !isDone && (
                            <Button
                                variant={needsFindingFirst ? 'primary' : 'secondary'}
                                size="sm"
                                className={`w-full ${needsFindingFirst ? 'bg-rose-600 hover:bg-rose-700 ring-rose-600' : ''}`}
                                onClick={() => setFindingModalOpen(true)}
                                icon={<IconPlus />}
                            >
                                Bulgu Kaydı Oluştur {hasFindings ? `(${test.findings?.length})` : ''}
                            </Button>
                        )}

                        {/* Madde 6: devam eden açık bulguya referans ile ilerletme */}
                        {needsFindingFirst && openFindings.length > 0 && (
                            <div className="p-3 bg-amber-50 border border-amber-200 rounded-xl space-y-2">
                                <p className="text-xs font-semibold text-amber-700">Ya da mevcut açık bir bulguyu referans alarak ilerletin</p>
                                <select
                                    value={referencedFindingId}
                                    onChange={e => setReferencedFindingId(e.target.value)}
                                    className="w-full px-2.5 py-2 text-xs border border-amber-300 rounded-lg bg-white"
                                >
                                    <option value="">Açık bulgu seçiniz...</option>
                                    {openFindings.map(f => (
                                        <option key={f.id} value={f.id}>{f.findingId} — {f.summary || ''}</option>
                                    ))}
                                </select>
                                {referencedFindingId && (
                                    <>
                                        <textarea
                                            value={referenceReason}
                                            onChange={e => setReferenceReason(e.target.value)}
                                            rows={2}
                                            placeholder="Referans gerekçesi (opsiyonel)..."
                                            className="w-full px-2.5 py-2 text-xs border border-amber-300 rounded-lg resize-none"
                                        />
                                        <Button variant="primary" size="sm" className="w-full" onClick={handleReference} disabled={saving} icon={<IconLink />}>
                                            Referans ile Onaya Gönder
                                        </Button>
                                    </>
                                )}
                            </div>
                        )}

                        <div>
                            <label className="text-sm font-semibold text-slate-700 block mb-1.5">
                                Kontrol Sonucu Açıklaması
                            </label>
                            <textarea
                                disabled={isDone}
                                value={form.resultText}
                                onChange={e => setForm(p => ({ ...p, resultText: e.target.value }))}
                                rows={3}
                                placeholder="Test sonucuna ilişkin açıklama..."
                                className="w-full border border-slate-200 rounded-lg px-3 py-2 text-sm outline-none focus:border-blue-400 focus:ring-2 focus:ring-blue-100 resize-none disabled:bg-slate-50 disabled:text-slate-500"
                            />
                        </div>
                        <div>
                            <label className="text-sm font-semibold text-slate-700 block mb-1.5">
                                Kanıt Özeti
                            </label>
                            <textarea
                                disabled={isDone}
                                value={form.evidenceSummary}
                                onChange={e => setForm(p => ({ ...p, evidenceSummary: e.target.value }))}
                                rows={2}
                                placeholder="İncelenen kanıtların özeti..."
                                className="w-full border border-slate-200 rounded-lg px-3 py-2 text-sm outline-none focus:border-blue-400 focus:ring-2 focus:ring-blue-100 resize-none disabled:bg-slate-50 disabled:text-slate-500"
                            />
                        </div>
                    </div>
                )}

                {/* İlgili bulgular */}
                {test.findings && test.findings.length > 0 && (
                    <div>
                        <p className="text-sm font-semibold text-slate-700 mb-2">İlgili Bulgular ({test.findings.length})</p>
                        <div className="space-y-2">
                            {test.findings.map(f => {
                                const sv = severityConfig[f.severity];
                                return (
                                    <Link key={f.id} href={`/findings/${f.id}`}
                                        className="flex items-center gap-2 p-2.5 bg-slate-50 hover:bg-blue-50 rounded-lg border border-slate-200 hover:border-blue-300 transition-all">
                                        {sv && <StatusBadge variant={sv.variant}>{sv.label}</StatusBadge>}
                                        <span className="font-mono text-xs text-blue-700 font-semibold">{f.findingId}</span>
                                        <svg className="w-3 h-3 text-slate-400 ml-auto" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" /></svg>
                                    </Link>
                                );
                            })}
                        </div>
                    </div>
                )}
            </div>

            {findingModalOpen && (
                <CreateFindingModal
                    isOpen={findingModalOpen}
                    onClose={() => setFindingModalOpen(false)}
                    onSuccess={() => { setFindingModalOpen(false); onRefresh(); }}
                    prefillData={{ controlId: test.control.id, controlTestId: test.id, directorateId: test.directorate?.id }}
                />
            )}

            {/* Geri gönderme gerekçesi — gerekçe zorunlu */}
            <ReasonModal
                open={reasonModal === 'return'}
                title="Geri Gönder"
                description="Test, testi yapan kullanıcıya düzeltme için geri gönderilecek."
                confirmLabel="Onayla"
                reasonRequired
                saving={saving}
                onConfirm={handleReturnConfirm}
                onClose={() => setReasonModal(null)}
            />

            {/* Final onay iptali — gerekçe opsiyonel, modal onayı emin misiniz yerine geçer */}
            <ReasonModal
                open={reasonModal === 'cancel'}
                title="Final Onayı İptal Et"
                description="Bu final onaylı test iptal edilecek. Emin misiniz?"
                confirmLabel="Onayla"
                reasonRequired={false}
                saving={saving}
                onConfirm={handleCancelFinalConfirm}
                onClose={() => setReasonModal(null)}
            />
        </div>
    );
}

// ─── Page ─────────────────────────────────────────────────────────────────────

function ControlTestingPageContent() {
    const { error: showError } = useToast();
    const searchParams = useSearchParams();
    const recordId = searchParams.get('recordId');

    const [tests, setTests] = useState<ControlTest[]>([]);
    const [loading, setLoading] = useState(true);
    const [activeTest, setActiveTest] = useState<ControlTest | null>(null);
    const [users, setUsers] = useState<{ id: string; firstName: string; lastName: string; email: string }[]>([]);

    const [searchQuery, setSearchQuery] = useState('');
    const [activeFilters, setActiveFilters] = useState<Record<string, string>>({});
    const [colFilters, setColFilters] = useState<Record<string, string>>({});
    const [selectedMonth, setSelectedMonth] = useState<number | null>(new Date().getMonth()); // 0-11 or null for all
    const [page, setPage] = useState(1);
    const pageSize = 25;

    const load = useCallback(async () => {
        setLoading(true);
        try {
            const [testsRes, usersRes] = await Promise.allSettled([
                api.getAllControlTests({ limit: 2000 }) as Promise<{ data: ControlTest[] }>,
                api.getUsers() as Promise<any[]>,
            ]);

            if (testsRes.status === 'fulfilled') {
                setTests(testsRes.value?.data || []);
            } else {
                showError('Hata', 'Test kayıtları yüklenemedi.');
                setTests([]);
            }

            if (usersRes.status === 'fulfilled') {
                setUsers(usersRes.value || []);
            }
            // Kullanıcı yüklenemezse sessizce [] bırak
        } finally {
            setLoading(false);
        }
    }, []);

    useEffect(() => { load(); }, [load]);

    useEffect(() => {
        if (recordId && tests.length > 0) {
            const found = tests.find(t => t.id === recordId);
            if (found) {
                setActiveTest(found);
                const d = new Date(found.plannedDate);
                setSelectedMonth(d.getMonth());
            }
        }
    }, [recordId, tests]);

    // ── KPIs (ay filtresine göre) ─────────────────────────────────────────

    const monthFiltered = useMemo(() => {
        if (selectedMonth === null) return tests;
        return tests.filter(t => {
            const d = new Date(t.plannedDate);
            return d.getMonth() === selectedMonth && d.getFullYear() === new Date().getFullYear();
        });
    }, [tests, selectedMonth]);

    const kpis = useMemo(() => {
        const total      = monthFiltered.length;
        const bekliyor   = monthFiltered.filter(t => t.status === 'BEKLIYOR').length;
        const devam      = monthFiltered.filter(t => t.status === 'DEVAM_EDIYOR').length;
        const tamamlandi = monthFiltered.filter(t => t.status === 'TAMAMLANDI').length;
        const onaylandi  = monthFiltered.filter(t => t.status === 'ONAYLANDI').length;
        const bulgulu    = monthFiltered.filter(t => t.findingStatus === 'BULGUSU_VAR').length;
        const overdue    = monthFiltered.filter(isOverdue).length;
        return { total, bekliyor, devam, tamamlandi, onaylandi, bulgulu, overdue };
    }, [monthFiltered]);

    // ── Filter ────────────────────────────────────────────────────────────────

    const filtered = useMemo(() => {
        return monthFiltered.filter(t => {
            if (searchQuery) {
                const q = searchQuery.toLowerCase();
                const txt = [t.testNo, t.control.controlId, t.control.name, t.directorate?.name, t.summary].filter(Boolean).join(' ').toLowerCase();
                if (!txt.includes(q)) return false;
            }
            if (activeFilters.status && activeFilters.status !== 'all' && t.status !== activeFilters.status) return false;
            if (activeFilters.findingStatus && t.findingStatus !== activeFilters.findingStatus) return false;
            if (activeFilters.directorateId && t.directorate?.id !== activeFilters.directorateId) return false;
            if (activeFilters.overdue === 'evet' && !isOverdue(t)) return false;
            return true;
        });
    }, [monthFiltered, searchQuery, activeFilters]);

    // KPI click-to-filter yardımcıları (aynı karta tekrar tıklanınca filtre kalkar)
    const toggleStatusFilter = (status: string) => {
        setActiveFilters(p => (p.status === status ? {} : { status }) as Record<string, string>);
        setPage(1);
    };
    const hasAnyFilter = Object.values(activeFilters).some(v => v && v !== 'all');

    // ── Gelişmiş filtre alanları ──────────────────────────────────────────────

    const advancedFields: AdvancedFilterField[] = useMemo(() => [
        {
            type: 'select', key: 'status', label: 'Statü',
            value: activeFilters['status'] || '',
            onChange: (v: string) => { setActiveFilters(p => ({ ...p, status: v })); setPage(1); },
            options: Object.entries(statusConfig).map(([k, v]) => ({ value: k, label: v.label })),
        },
        {
            type: 'select', key: 'findingStatus', label: 'Kontrol Sonucu',
            value: activeFilters['findingStatus'] || '',
            onChange: (v: string) => { setActiveFilters(p => ({ ...p, findingStatus: v })); setPage(1); },
            options: Object.entries(findingStatusConfig).map(([k, v]) => ({ value: k, label: v.label })),
        },
    ], [activeFilters]);

    // ── Aktif filtre chip'leri ────────────────────────────────────────────────

    const filterLabels: Record<string, string> = { status: 'Statü', findingStatus: 'Kontrol Sonucu', overdue: 'Gecikmiş', directorateId: 'Direktörlük' };
    const filterValueLabel = (key: string, value: string): string => {
        if (key === 'status') return statusConfig[value]?.label ?? value;
        if (key === 'findingStatus') return findingStatusConfig[value]?.label ?? value;
        if (key === 'overdue') return 'Evet';
        return value;
    };
    const activeChips: ActiveFilterChip[] = useMemo(() => {
        const chips: ActiveFilterChip[] = [];
        if (searchQuery) chips.push({ key: 'search', label: 'Arama', value: searchQuery, onRemove: () => { setSearchQuery(''); setPage(1); } });
        Object.entries(activeFilters).forEach(([k, v]) => {
            if (v && v !== 'all') chips.push({
                key: k, label: filterLabels[k] ?? k, value: filterValueLabel(k, v),
                onRemove: () => { setActiveFilters(p => ({ ...p, [k]: '' })); setPage(1); },
            });
        });
        return chips;
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [searchQuery, activeFilters]);

    const clearAll = () => { setSearchQuery(''); setActiveFilters({}); setColFilters({}); setPage(1); };

    // ── Columns ───────────────────────────────────────────────────────────────

    const columns: ColumnDef<ControlTest>[] = useMemo(() => [
        {
            key: 'testNo',
            header: 'Test No',
            sortable: true,
            defaultWidth: 130,
            filter: { type: 'text', placeholder: 'Test No...', fn: (t: ControlTest, v) => t.testNo.toLowerCase().includes(v.toLowerCase()) },
            render: (t) => (
                <button onClick={() => setActiveTest(t)} className="font-mono text-xs font-bold text-blue-700 hover:underline text-left cursor-pointer">
                    {t.testNo}
                </button>
            ),
        },
        {
            key: 'control',
            header: 'Kontrol',
            defaultWidth: 220,
            filter: { type: 'text', placeholder: 'Kontrol adı...', fn: (t: ControlTest, v) => (t.control.name + ' ' + t.control.controlId).toLowerCase().includes(v.toLowerCase()) },
            render: (t) => (
                <div className="min-w-0">
                    <p className="text-xs font-semibold text-slate-700 truncate">{t.control.name}</p>
                    <p className="text-[10px] text-slate-400 font-mono">{t.control.controlId}</p>
                </div>
            ),
        },
        {
            key: 'directorate',
            header: 'Direktörlük',
            sortable: true,
            defaultWidth: 160,
            filter: { type: 'text', placeholder: 'Direktörlük...', fn: (t: ControlTest, v) => (t.directorate?.name || '').toLowerCase().includes(v.toLowerCase()) },
            render: (t) => (
                <span className="text-xs text-slate-600 truncate block max-w-[150px]">{t.directorate?.name || '—'}</span>
            ),
        },
        {
            key: 'plannedDate',
            header: 'Plan Tarihi',
            sortable: true,
            defaultWidth: 110,
            render: (t) => {
                const overdue = isOverdue(t);
                return (
                    <span className={`inline-flex items-center gap-1 text-xs font-medium ${overdue ? 'text-red-600' : 'text-slate-700'}`}>
                        {fmt(t.plannedDate)}
                        {overdue && <IconWarning className="w-3 h-3" />}
                    </span>
                );
            },
        },
        {
            key: 'status',
            header: 'Statü',
            sortable: true,
            defaultWidth: 140,
            filter: { type: 'select', options: Object.entries(statusConfig).map(([k, v]) => ({ value: k, label: v.label })), fn: (t: ControlTest, v) => t.status === v },
            render: (t) => {
                const sc = statusConfig[t.status];
                const fc = t.findingStatus ? findingStatusConfig[t.findingStatus] : null;
                return (
                    <div className="flex flex-col gap-1">
                        {sc && <StatusBadge variant={sc.variant}>{sc.label}</StatusBadge>}
                        {fc && <StatusBadge variant={fc.variant} dot>{fc.label}</StatusBadge>}
                    </div>
                );
            },
        },
        {
            key: 'findings',
            header: 'Bulgular',
            defaultWidth: 80,
            render: (t) => {
                const cnt = t.findings?.length || 0;
                return cnt > 0
                    ? <span className="px-2 py-0.5 bg-red-100 text-red-700 text-xs font-bold rounded-full border border-red-200">{cnt}</span>
                    : <span className="text-slate-300 text-xs">—</span>;
            },
        },
        {
            key: 'actions',
            header: '',
            defaultWidth: 60,
            render: (t) => (
                <button onClick={() => setActiveTest(t)} className="p-1.5 text-slate-400 hover:text-blue-600 hover:bg-blue-50 rounded transition-colors cursor-pointer" title="Aç">
                    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" /></svg>
                </button>
            ),
        },
    ], []);

    const colFiltered = useMemo(() => {
        if (!Object.values(colFilters).some(v => v)) return filtered;
        return filtered.filter(t => columns.every(col => {
            const val = colFilters[col.key];
            return !val || !col.filter?.fn || col.filter.fn(t, val);
        }));
    }, [filtered, colFilters, columns]);

    const paginated = useMemo(() => colFiltered.slice((page - 1) * pageSize, page * pageSize), [colFiltered, page]);

    // ─────────────────────────────────────────────────────────────────────────

    return (
        <PageShell fullHeight>
            <div className="flex flex-1 min-h-0 gap-4 pb-4">
                {/* List Panel */}
                <div className={`flex flex-col ${activeTest ? 'flex-1' : 'w-full'} min-w-0 overflow-y-auto`}>
                    <PageHeader
                        title="Kontrol Testleri"
                        description="Kontrollere ait test kayıtlarını yönetin — başlatın, tamamlayın, onaylayın"
                        breadcrumbs={[{ label: 'Kontrol Testleri' }]}
                    />

                    {/* Ay seçici — QuickFilterBar chip diliyle hizalı (13 öğeli özel picker) */}
                    <div className="flex flex-wrap items-center gap-2 mb-3">
                        <span className="inline-flex items-center gap-1.5 text-xs font-medium text-slate-400 mr-1">
                            <IconCalendar className="w-3.5 h-3.5" />
                            Ay:
                        </span>
                        <button
                            type="button"
                            onClick={() => { setSelectedMonth(null); setPage(1); }}
                            aria-pressed={selectedMonth === null}
                            className={`inline-flex items-center h-8 px-3 rounded-full text-xs font-medium border transition-colors duration-150 cursor-pointer ${
                                selectedMonth === null
                                    ? 'bg-blue-600 border-blue-600 text-white shadow-sm'
                                    : 'bg-white border-slate-200 text-slate-600 hover:border-blue-300 hover:text-blue-700 hover:bg-blue-50/50'
                            }`}
                        >
                            Tümü
                        </button>
                        {MONTHS_SHORT.map((m, i) => {
                            const isCurrentMonth = i === new Date().getMonth();
                            return (
                                <button
                                    key={i}
                                    type="button"
                                    onClick={() => { setSelectedMonth(i); setPage(1); }}
                                    aria-pressed={selectedMonth === i}
                                    className={`inline-flex items-center h-8 px-2.5 rounded-full text-xs font-medium border transition-colors duration-150 cursor-pointer ${
                                        selectedMonth === i
                                            ? 'bg-blue-600 border-blue-600 text-white shadow-sm'
                                            : isCurrentMonth
                                                ? 'bg-blue-50 border-blue-200 text-blue-700 hover:bg-blue-100'
                                                : 'bg-white border-slate-200 text-slate-600 hover:border-blue-300 hover:text-blue-700 hover:bg-blue-50/50'
                                    }`}
                                    title={MONTHS_TR[i]}
                                >
                                    {m}
                                </button>
                            );
                        })}
                    </div>

                    {/* KPI'lar — click-to-filter */}
                    <KpiGrid columns={4}>
                        <KpiCard title="Toplam" value={kpis.total} variant="default"
                            active={!hasAnyFilter}
                            onClick={() => { setActiveFilters({}); setPage(1); }} />
                        <KpiCard title="Bekliyor" value={kpis.bekliyor} variant="default"
                            active={activeFilters.status === 'BEKLIYOR'}
                            onClick={() => toggleStatusFilter('BEKLIYOR')} />
                        <KpiCard title="Devam" value={kpis.devam} variant="warning"
                            active={activeFilters.status === 'DEVAM_EDIYOR'}
                            onClick={() => toggleStatusFilter('DEVAM_EDIYOR')} />
                        <KpiCard title="Tamamlandı" value={kpis.tamamlandi} variant="primary"
                            active={activeFilters.status === 'TAMAMLANDI'}
                            onClick={() => toggleStatusFilter('TAMAMLANDI')} />
                        <KpiCard title="Onaylı" value={kpis.onaylandi} variant="success"
                            active={activeFilters.status === 'ONAYLANDI'}
                            onClick={() => toggleStatusFilter('ONAYLANDI')} />
                        <KpiCard title="Bulgulu" value={kpis.bulgulu} variant="critical"
                            active={activeFilters.findingStatus === 'BULGUSU_VAR'}
                            onClick={() => { setActiveFilters(p => (p.findingStatus === 'BULGUSU_VAR' ? {} : { findingStatus: 'BULGUSU_VAR' }) as Record<string, string>); setPage(1); }} />
                        <KpiCard title="Gecikmiş" value={kpis.overdue} variant="high"
                            active={activeFilters.overdue === 'evet'}
                            onClick={() => { setActiveFilters(p => (p.overdue === 'evet' ? {} : { overdue: 'evet' }) as Record<string, string>); setPage(1); }} />
                    </KpiGrid>

                    {/* Gelişmiş filtre paneli */}
                    <AdvancedFilterPanel
                        searchValue={searchQuery}
                        onSearchChange={v => { setSearchQuery(v); setPage(1); }}
                        searchPlaceholder="Test No, Kontrol adı, Direktörlük ara..."
                        fields={advancedFields}
                        activeCount={Object.values(activeFilters).filter(v => v && v !== 'all').length}
                        onClearAll={clearAll}
                    />

                    {/* Aktif filtre chip'leri */}
                    <ActiveFilterChips chips={activeChips} onClearAll={clearAll} />

                    <DataTable
                        columns={columns}
                        data={paginated}
                        rowKey={t => t.id}
                        loading={loading}
                        totalCount={colFiltered.length}
                        page={page}
                        pageSize={pageSize}
                        onPageChange={setPage}
                        storageKey="control-tests-v1"
                        emptyTitle="Test kaydı bulunamadı"
                        emptyDescription="Kontrolleri aktif yaparak test kayıtlarını otomatik oluşturun."
                        onRowClick={t => setActiveTest(t)}
                        columnFilters={colFilters}
                        onColumnFilterChange={(k, v) => { setColFilters(p => ({ ...p, [k]: v })); setPage(1); }}
                        stickyFirstColumn
                        onRefresh={load}
                        toolbar={
                            <SavedViewMenu
                                storageKey="control-tests-v1"
                                getPayload={() => ({ search: searchQuery, filters: activeFilters, columnFilters: colFilters, selectedMonth })}
                                onApply={(p) => {
                                    setSearchQuery(typeof p.search === 'string' ? p.search : '');
                                    setActiveFilters((p.filters as Record<string, string>) || {});
                                    setColFilters((p.columnFilters as Record<string, string>) || {});
                                    setSelectedMonth(typeof p.selectedMonth === 'number' ? p.selectedMonth : null);
                                    setPage(1);
                                }}
                            />
                        }
                    />
                </div>

                {/* Workspace Panel */}
                {activeTest && (
                    <div className="w-96 flex-shrink-0 bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
                        <WorkspacePanel
                            test={activeTest}
                            users={users}
                            onRefresh={() => { load(); setActiveTest(null); }}
                            onClose={() => setActiveTest(null)}
                        />
                    </div>
                )}
            </div>
        </PageShell>
    );
}

export default function ControlTestingPage() {
    return (
        <Suspense fallback={<PageShell><div className="p-6 text-center text-sm text-slate-500">Yükleniyor...</div></PageShell>}>
            <ControlTestingPageContent />
        </Suspense>
    );
}
