'use client';

import { useState, useEffect, useMemo, useCallback, Suspense } from 'react';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import api from '@/lib/api';
import { PageHeader, StatusBadge, Button, DataTable, FilterBar } from '@/components/ui';
import type { ColumnDef } from '@/components/ui';
import { useToast } from '@/components/ui/Toast';
import { CreateFindingModal } from '@/components/modals/CreateFindingModal';
import { FileUpload, type AttachmentMeta } from '@/components/ui';
import { useAuth } from '@/components/auth';

// ─── Types ────────────────────────────────────────────────────────────────────

type BV = 'critical' | 'high' | 'medium' | 'low' | 'info' | 'success' | 'warning' | 'neutral' | 'primary';

interface ControlTest {
    id: string;
    testNo: string;
    controlId: string;
    plannedDate: string;
    completedAt?: string | null;
    status: string;
    findingStatus?: string | null;
    resultText?: string | null;
    evidenceSummary?: string | null;
    assigneeId?: string | null;
    isAutoGenerated: boolean;
    summary?: string | null;
    control: {
        id: string;
        controlId: string;
        name: string;
        type: string;
        frequency: string;
        gmy?: string | null;
    };
    directorate?: { id: string; name: string; code?: string | null } | null;
    findings?: { id: string; findingId: string; severity: string; resolutionStatus: string }[];
    attachments?: { id: string; fileName: string; originalName: string; mimeType: string; sizeBytes: number }[];
}

// ─── Config ───────────────────────────────────────────────────────────────────

const statusConfig: Record<string, { label: string; variant: BV }> = {
    BEKLIYOR:         { label: 'Bekliyor',           variant: 'neutral' },
    DEVAM_EDIYOR:     { label: 'Devam Ediyor',       variant: 'warning' },
    TAMAMLANDI:       { label: 'Onay Bekliyor',      variant: 'info' },
    GERI_GONDERILDI:  { label: 'Geri Gönderildi',    variant: 'critical' },
    ONAYLANDI:        { label: 'Onaylandı',          variant: 'success' },
    IPTAL:            { label: 'İptal Edildi',       variant: 'neutral' },
};

const findingStatusConfig: Record<string, { label: string; variant: BV }> = {
    BULGUSU_YOK: { label: 'Bulgu Yok', variant: 'success' },
    BULGUSU_VAR: { label: 'Bulgu Var', variant: 'critical' },
};

const severityConfig: Record<string, { label: string; variant: BV }> = {
    CRITICAL: { label: 'KZ', variant: 'critical' },
    HIGH:     { label: 'KD', variant: 'high' },
    MEDIUM:   { label: 'ÖK', variant: 'medium' },
    LOW:      { label: 'Düşük', variant: 'low' },
};

const fmt = (d?: string | null) => {
    if (!d) return '—';
    const dt = new Date(d);
    return isNaN(dt.getTime()) ? '—' : dt.toLocaleDateString('tr-TR');
};

const MONTHS_TR = ['Ocak', 'Şubat', 'Mart', 'Nisan', 'Mayıs', 'Haziran', 'Temmuz', 'Ağustos', 'Eylül', 'Ekim', 'Kasım', 'Aralık'];
const MONTHS_SHORT = ['Oca', 'Şub', 'Mar', 'Nis', 'May', 'Haz', 'Tem', 'Ağu', 'Eyl', 'Eki', 'Kas', 'Ara'];

// ─── WorkspacePanel ──────────────────────────────────────────────────────────

function WorkspacePanel({
    test, users, onRefresh, onClose,
}: {
    test: ControlTest;
    users: { id: string; firstName: string; lastName: string; email: string }[];
    onRefresh: () => void;
    onClose: () => void;
}) {
    const { success, error: showError } = useToast();
    const [saving, setSaving] = useState(false);
    const [findingModalOpen, setFindingModalOpen] = useState(false);
    const hasFindings = (test.findings?.length ?? 0) > 0;

    // Madde 6: devam eden açık bulguyu referans alarak ilerletme
    const [openFindings, setOpenFindings] = useState<{ id: string; findingId: string; summary?: string | null }[]>([]);
    const [referencedFindingId, setReferencedFindingId] = useState('');
    const [referenceReason, setReferenceReason] = useState('');
    const [form, setForm] = useState({
        resultText: test.resultText || '',
        evidenceSummary: test.evidenceSummary || '',
        // Bağlı açık bulgu varsa BULGUSU_VAR ile başla — test.findingStatus yalnızca test
        // tamamlanınca dolar, o ana kadar tek doğru sinyal bağlı bulgu kaydının varlığıdır.
        findingStatus: test.findingStatus || (hasFindings ? 'BULGUSU_VAR' : 'BULGUSU_YOK'),
    });

    // Madde 5 bug fix: kullanıcı "Bulgu Var" seçip yeni bulgu ekledikten sonra panel
    // yeniden açıldığında (test/hasFindings değiştiğinde) seçim "Bulgu Yok"a düşmemeli —
    // bağlı bulgu varsa seçim her zaman BULGUSU_VAR'a senkronize edilir.
    useEffect(() => {
        if (hasFindings) {
            setForm(p => (p.findingStatus === 'BULGUSU_VAR' ? p : { ...p, findingStatus: 'BULGUSU_VAR' }));
        }
    }, [hasFindings, test.id]);

    // Bu kontrole ait, henüz kapanmamış diğer bulguları getir (referans seçeneği için)
    useEffect(() => {
        if (hasFindings) return;
        api.getFindings({ controlId: test.control.id, limit: 100 })
            .then((res: any) => {
                const list = Array.isArray(res) ? res : (res?.data || []);
                setOpenFindings(list.filter((f: any) => f.status !== 'CLOSED'));
            })
            .catch(() => setOpenFindings([]));
    }, [test.control.id, hasFindings]);

    const canStart    = test.status === 'BEKLIYOR';
    const canComplete = test.status === 'DEVAM_EDIYOR' || test.status === 'GERI_GONDERILDI';
    const canApprove  = test.status === 'TAMAMLANDI';
    const canReturn   = test.status === 'TAMAMLANDI';
    const isDone      = test.status === 'ONAYLANDI';
    const isCancelled = test.status === 'IPTAL';
    // BULGUSU_VAR seçildiyse bulgu eklenene kadar "Testi Tamamla" disabled
    const needsFindingFirst = form.findingStatus === 'BULGUSU_VAR' && !hasFindings;
    const completeBlockedReason = needsFindingFirst
        ? 'Önce "Bulgu Kaydı Oluştur" ile bir bulgu kaydı ekleyin.'
        : null;

    const handleStart = async () => {
        setSaving(true);
        try {
            await api.startControlTest(test.id);
            success('Başlatıldı', 'Test Devam Ediyor statüsüne alındı.');
            onRefresh();
        } catch { showError('Hata', 'Test başlatılamadı.'); }
        finally { setSaving(false); }
    };

    const handleComplete = async () => {
        setSaving(true);
        try {
            await api.completeControlTest(test.id, {
                findingStatus: form.findingStatus,
                resultText: form.resultText,
                evidenceSummary: form.evidenceSummary,
            });
            success('Tamamlandı', 'Test sonucu kaydedildi, 2. kontrolcü onayına gönderildi.');
            onRefresh();
        } catch (err: any) { showError('Hata', err.message || 'Test tamamlanamadı.'); }
        finally { setSaving(false); }
    };

    const handleReference = async () => {
        if (!referencedFindingId) return;
        setSaving(true);
        try {
            await api.completeControlTest(test.id, {
                referencedFindingId,
                referenceReason,
            });
            success('İlerletildi', 'Test, referans verilen açık bulgu ile 2. kontrolcü onayına gönderildi.');
            onRefresh();
        } catch (err: any) { showError('Hata', err.message || 'Referans ile ilerletilemedi.'); }
        finally { setSaving(false); }
    };

    const handleApprove = async () => {
        setSaving(true);
        try {
            await api.approveControlTest(test.id);
            success('Onaylandı', 'Test onaylandı.');
            onRefresh();
        } catch { showError('Hata', 'Test onaylanamadı.'); }
        finally { setSaving(false); }
    };

    const handleReturn = async () => {
        const reason = prompt('Geri gönderme gerekçesini yazın (zorunlu):');
        if (!reason || !reason.trim()) return;
        setSaving(true);
        try {
            await api.returnControlTest(test.id, reason);
            success('Geri Gönderildi', 'Test testi yapan kullanıcıya düzeltme için geri gönderildi.');
            onRefresh();
        } catch { showError('Hata', 'Geri gönderilemedi.'); }
        finally { setSaving(false); }
    };

    const { user } = useAuth();
    const isSystemAdmin = user?.role?.name === 'SYSTEM_ADMIN';

    const handleCancelFinal = async () => {
        const reason = prompt('Final onaylı testi iptal etme gerekçesini yazın:') || '';
        if (!confirm('Bu final onaylı test iptal edilecek. Emin misiniz?')) return;
        setSaving(true);
        try {
            await api.cancelControlTest(test.id, reason);
            success('İptal Edildi', 'Final onaylı test iptal edildi.');
            onRefresh();
        } catch { showError('Hata', 'Test iptal edilemedi.'); }
        finally { setSaving(false); }
    };

    const stCfg = statusConfig[test.status] || { label: test.status, variant: 'neutral' as BV };

    return (
        <div className="h-full flex flex-col bg-white border-l border-slate-200">
            {/* Header */}
            <div className="flex items-center justify-between px-5 py-4 border-b border-slate-100 bg-slate-50">
                <div>
                    <div className="flex items-center gap-2 mb-1">
                        <span className="font-mono text-xs font-bold text-violet-700">{test.testNo}</span>
                        <StatusBadge variant={stCfg.variant}>{stCfg.label}</StatusBadge>
                        {test.findingStatus && (
                            <StatusBadge variant={findingStatusConfig[test.findingStatus]?.variant || 'neutral'}>
                                {findingStatusConfig[test.findingStatus]?.label || test.findingStatus}
                            </StatusBadge>
                        )}
                    </div>
                    <p className="text-sm font-semibold text-slate-800 max-w-xs truncate">{test.control.name}</p>
                    <p className="text-xs text-slate-400 mt-0.5">
                        {test.directorate?.name && <span className="mr-2">📍 {test.directorate.name}</span>}
                        <span>📅 Plan: {fmt(test.plannedDate)}</span>
                        {test.completedAt && <span className="ml-2">✅ {fmt(test.completedAt)}</span>}
                    </p>
                </div>
                <button onClick={onClose} className="p-1.5 text-slate-400 hover:text-slate-700 rounded-lg hover:bg-slate-100">
                    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" /></svg>
                </button>
            </div>

            <div className="flex-1 overflow-y-auto p-5 space-y-5">
                {/* Kontrol Bilgisi */}
                <div className="bg-slate-50 rounded-xl p-4 space-y-2 text-sm">
                    <div className="flex items-center justify-between">
                        <span className="text-xs text-slate-500 font-semibold uppercase tracking-wide">Kontrol</span>
                        <Link href={`/controls/${test.control.id}`} className="text-violet-600 hover:underline text-xs font-mono">{test.control.controlId}</Link>
                    </div>
                    <p className="text-slate-800 font-medium">{test.control.name}</p>
                    {test.control.gmy && <p className="text-xs text-slate-500">👤 {test.control.gmy}</p>}
                </div>

                {/* Kanıt Ekleri — Bulgu Var/Yok'tan bağımsız her zaman görünür */}
                <div>
                    <FileUpload
                        label="Kanıt Ekleri"
                        disabled={isDone}
                        attachments={(test.attachments ?? []) as AttachmentMeta[]}
                        onUpload={async (meta) => {
                            try {
                                await api.addControlTestAttachment(test.id, meta);
                                success('Yüklendi', `${meta.originalName} eklendi.`);
                                onRefresh();
                            } catch { showError('Hata', 'Dosya eklenemedi.'); }
                        }}
                        onRemove={async (att) => {
                            if (!att.id) return;
                            try {
                                await api.removeControlTestAttachment(test.id, att.id);
                                onRefresh();
                            } catch { showError('Hata', 'Dosya silinemedi.'); }
                        }}
                    />
                </div>

                {/* İş Akışı Butonları */}
                {!isDone && !isCancelled && (
                    <div className="space-y-2">
                        <p className="text-xs font-semibold text-slate-500 uppercase tracking-wide">İş Akışı</p>
                        {canStart && (
                            <Button variant="primary" size="sm" className="w-full" onClick={handleStart} disabled={saving}>
                                ▶ Testi Başlat
                            </Button>
                        )}
                        {canComplete && (
                            <div>
                                <Button variant="primary" size="sm" className="w-full"
                                    onClick={handleComplete}
                                    disabled={saving || !form.findingStatus || needsFindingFirst}
                                    title={completeBlockedReason ?? undefined}>
                                    ✓ Testi Tamamla ve Onaya Gönder
                                </Button>
                                {completeBlockedReason && (
                                    <p className="text-[11px] text-amber-600 mt-1.5">{completeBlockedReason}</p>
                                )}
                            </div>
                        )}
                        {canApprove && (
                            <Button variant="primary" size="sm" className="w-full" onClick={handleApprove} disabled={saving}>
                                ✅ Onayla (2. Kontrolcü)
                            </Button>
                        )}
                        {canReturn && (
                            <Button variant="secondary" size="sm" className="w-full" onClick={handleReturn} disabled={saving}>
                                ↩ Geri Gönder
                            </Button>
                        )}
                    </div>
                )}

                {/* Final onaylı testi iptal — yalnızca SYSTEM_ADMIN */}
                {isDone && isSystemAdmin && (
                    <div className="space-y-2">
                        <p className="text-xs font-semibold text-slate-500 uppercase tracking-wide">Yönetici İşlemleri</p>
                        <Button variant="secondary" size="sm" className="w-full text-red-600 border-red-200 hover:bg-red-50" onClick={handleCancelFinal} disabled={saving}>
                            ⛔ Final Onayı İptal Et
                        </Button>
                    </div>
                )}

                {/* Test Sonucu Formu */}
                {(canComplete || isDone) && (
                    <div className="space-y-4">
                        <div>
                            <p className="text-xs font-semibold text-slate-600 uppercase tracking-wide mb-2">Kontrol Sonucu</p>
                            <div className="grid grid-cols-2 gap-2">
                                {['BULGUSU_YOK', 'BULGUSU_VAR'].map(opt => (
                                    <button key={opt} type="button"
                                        disabled={isDone || (opt === 'BULGUSU_YOK' && hasFindings)}
                                        title={opt === 'BULGUSU_YOK' && hasFindings ? 'Bu teste bağlı bulgu kaydı var, sonuç Bulgu Yok olamaz.' : undefined}
                                        onClick={() => setForm(p => ({ ...p, findingStatus: opt }))}
                                        className={`p-3 rounded-xl border-2 text-sm font-semibold transition-all disabled:opacity-40 disabled:cursor-not-allowed ${
                                            form.findingStatus === opt
                                                ? opt === 'BULGUSU_YOK' ? 'border-emerald-400 bg-emerald-50 text-emerald-800' : 'border-red-400 bg-red-50 text-red-800'
                                                : 'border-slate-200 bg-white text-slate-600 hover:border-slate-300'
                                        } ${isDone ? 'opacity-60 cursor-default' : ''}`}
                                    >
                                        {opt === 'BULGUSU_YOK' ? '✅ Bulgu Yok' : '⚠ Bulgu Var'}
                                    </button>
                                ))}
                            </div>
                        </div>

                        {form.findingStatus === 'BULGUSU_VAR' && !isDone && (
                            <Button
                                variant={needsFindingFirst ? 'primary' : 'secondary'}
                                size="sm"
                                className={`w-full ${needsFindingFirst ? 'bg-rose-600 hover:bg-rose-700 ring-rose-600' : ''}`}
                                onClick={() => setFindingModalOpen(true)}
                            >
                                + Bulgu Kaydı Oluştur {hasFindings ? `(${test.findings?.length})` : ''}
                            </Button>
                        )}

                        {/* Madde 6: devam eden açık bulguya referans ile ilerletme */}
                        {needsFindingFirst && openFindings.length > 0 && (
                            <div className="p-3 bg-amber-50 border border-amber-200 rounded-xl space-y-2">
                                <p className="text-xs font-semibold text-amber-700">Ya da mevcut açık bir bulguyu referans alarak ilerletin</p>
                                <select
                                    value={referencedFindingId}
                                    onChange={e => setReferencedFindingId(e.target.value)}
                                    className="w-full px-2.5 py-2 text-xs border border-amber-300 rounded-lg bg-white"
                                >
                                    <option value="">Açık bulgu seçiniz...</option>
                                    {openFindings.map(f => (
                                        <option key={f.id} value={f.id}>{f.findingId} — {f.summary || ''}</option>
                                    ))}
                                </select>
                                {referencedFindingId && (
                                    <>
                                        <textarea
                                            value={referenceReason}
                                            onChange={e => setReferenceReason(e.target.value)}
                                            rows={2}
                                            placeholder="Referans gerekçesi (opsiyonel)..."
                                            className="w-full px-2.5 py-2 text-xs border border-amber-300 rounded-lg resize-none"
                                        />
                                        <Button variant="primary" size="sm" className="w-full" onClick={handleReference} disabled={saving}>
                                            🔗 Referans ile Onaya Gönder
                                        </Button>
                                    </>
                                )}
                            </div>
                        )}

                        <div>
                            <label className="text-xs font-semibold text-slate-600 uppercase tracking-wide block mb-1.5">
                                Kontrol Sonucu Açıklaması
                            </label>
                            <textarea
                                disabled={isDone}
                                value={form.resultText}
                                onChange={e => setForm(p => ({ ...p, resultText: e.target.value }))}
                                rows={3}
                                placeholder="Test sonucuna ilişkin açıklama..."
                                className="w-full border border-slate-200 rounded-lg px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-violet-300 resize-none disabled:bg-slate-50 disabled:text-slate-500"
                            />
                        </div>
                        <div>
                            <label className="text-xs font-semibold text-slate-600 uppercase tracking-wide block mb-1.5">
                                Kanıt Özeti
                            </label>
                            <textarea
                                disabled={isDone}
                                value={form.evidenceSummary}
                                onChange={e => setForm(p => ({ ...p, evidenceSummary: e.target.value }))}
                                rows={2}
                                placeholder="İncelenen kanıtların özeti..."
                                className="w-full border border-slate-200 rounded-lg px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-violet-300 resize-none disabled:bg-slate-50 disabled:text-slate-500"
                            />
                        </div>
                    </div>
                )}

                {/* İlgili bulgular */}
                {test.findings && test.findings.length > 0 && (
                    <div>
                        <p className="text-xs font-semibold text-slate-500 uppercase tracking-wide mb-2">İlgili Bulgular ({test.findings.length})</p>
                        <div className="space-y-2">
                            {test.findings.map(f => {
                                const sv = severityConfig[f.severity];
                                return (
                                    <Link key={f.id} href={`/findings/${f.id}`}
                                        className="flex items-center gap-2 p-2.5 bg-slate-50 hover:bg-violet-50 rounded-lg border border-slate-200 hover:border-violet-300 transition-all">
                                        {sv && <StatusBadge variant={sv.variant}>{sv.label}</StatusBadge>}
                                        <span className="font-mono text-xs text-violet-700 font-semibold">{f.findingId}</span>
                                        <svg className="w-3 h-3 text-slate-400 ml-auto" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" /></svg>
                                    </Link>
                                );
                            })}
                        </div>
                    </div>
                )}
            </div>

            {findingModalOpen && (
                <CreateFindingModal
                    isOpen={findingModalOpen}
                    onClose={() => setFindingModalOpen(false)}
                    onSuccess={() => { setFindingModalOpen(false); onRefresh(); }}
                    prefillData={{ controlId: test.control.id, controlTestId: test.id, directorateId: test.directorate?.id }}
                />
            )}
        </div>
    );
}

// ─── Page ─────────────────────────────────────────────────────────────────────

function ControlTestingPageContent() {
    const { error: showError } = useToast();
    const searchParams = useSearchParams();
    const recordId = searchParams.get('recordId');

    const [tests, setTests] = useState<ControlTest[]>([]);
    const [loading, setLoading] = useState(true);
    const [activeTest, setActiveTest] = useState<ControlTest | null>(null);
    const [users, setUsers] = useState<{ id: string; firstName: string; lastName: string; email: string }[]>([]);

    const [searchQuery, setSearchQuery] = useState('');
    const [activeFilters, setActiveFilters] = useState<Record<string, string>>({});
    const [colFilters, setColFilters] = useState<Record<string, string>>({});
    const [selectedMonth, setSelectedMonth] = useState<number | null>(new Date().getMonth()); // 0-11 or null for all
    const [page, setPage] = useState(1);
    const pageSize = 25;

    const load = useCallback(async () => {
        setLoading(true);
        try {
            const [testsRes, usersRes] = await Promise.allSettled([
                api.getAllControlTests({ limit: 2000 }) as Promise<{ data: ControlTest[] }>,
                api.getUsers() as Promise<any[]>,
            ]);

            if (testsRes.status === 'fulfilled') {
                setTests(testsRes.value?.data || []);
            } else {
                showError('Hata', 'Test kayıtları yüklenemedi.');
                setTests([]);
            }

            if (usersRes.status === 'fulfilled') {
                setUsers(usersRes.value || []);
            }
            // Kullanıcı yüklenemezse sessizce [] bırak
        } finally {
            setLoading(false);
        }
    }, []);

    useEffect(() => { load(); }, [load]);

    useEffect(() => {
        if (recordId && tests.length > 0) {
            const found = tests.find(t => t.id === recordId);
            if (found) {
                setActiveTest(found);
                const d = new Date(found.plannedDate);
                setSelectedMonth(d.getMonth());
            }
        }
    }, [recordId, tests]);

    // ── KPIs (ay filtresine göre) ─────────────────────────────────────────

    const monthFiltered = useMemo(() => {
        if (selectedMonth === null) return tests;
        return tests.filter(t => {
            const d = new Date(t.plannedDate);
            return d.getMonth() === selectedMonth && d.getFullYear() === new Date().getFullYear();
        });
    }, [tests, selectedMonth]);

    const kpis = useMemo(() => {
        const total      = monthFiltered.length;
        const bekliyor   = monthFiltered.filter(t => t.status === 'BEKLIYOR').length;
        const devam      = monthFiltered.filter(t => t.status === 'DEVAM_EDIYOR').length;
        const tamamlandi = monthFiltered.filter(t => t.status === 'TAMAMLANDI').length;
        const onaylandi  = monthFiltered.filter(t => t.status === 'ONAYLANDI').length;
        const bulgulu    = monthFiltered.filter(t => t.findingStatus === 'BULGUSU_VAR').length;
        const overdue    = monthFiltered.filter(t => ['BEKLIYOR', 'DEVAM_EDIYOR'].includes(t.status) && new Date(t.plannedDate) < new Date()).length;
        return { total, bekliyor, devam, tamamlandi, onaylandi, bulgulu, overdue };
    }, [monthFiltered]);

    // ── Filter ────────────────────────────────────────────────────────────────

    const filtered = useMemo(() => {
        return monthFiltered.filter(t => {
            if (searchQuery) {
                const q = searchQuery.toLowerCase();
                const txt = [t.testNo, t.control.controlId, t.control.name, t.directorate?.name, t.summary].filter(Boolean).join(' ').toLowerCase();
                if (!txt.includes(q)) return false;
            }
            if (activeFilters.status && activeFilters.status !== 'all' && t.status !== activeFilters.status) return false;
            if (activeFilters.findingStatus && t.findingStatus !== activeFilters.findingStatus) return false;
            if (activeFilters.directorateId && t.directorate?.id !== activeFilters.directorateId) return false;
            return true;
        });
    }, [monthFiltered, searchQuery, activeFilters]);

    const filterConfigs = useMemo(() => [
        {
            key: 'status', label: 'Statü',
            value: activeFilters['status'] || '',
            onChange: (v: string) => { setActiveFilters(p => ({ ...p, status: v })); setPage(1); },
            options: Object.entries(statusConfig).map(([k, v]) => ({ value: k, label: v.label })),
        },
        {
            key: 'findingStatus', label: 'Kontrol Sonucu',
            value: activeFilters['findingStatus'] || '',
            onChange: (v: string) => { setActiveFilters(p => ({ ...p, findingStatus: v })); setPage(1); },
            options: Object.entries(findingStatusConfig).map(([k, v]) => ({ value: k, label: v.label })),
        },
    ], [activeFilters]);

    // ── Columns ───────────────────────────────────────────────────────────────

    const columns: ColumnDef<ControlTest>[] = useMemo(() => [
        {
            key: 'testNo',
            header: 'Test No',
            sortable: true,
            defaultWidth: 130,
            filter: { type: 'text', placeholder: 'Test No...', fn: (t: ControlTest, v) => t.testNo.toLowerCase().includes(v.toLowerCase()) },
            render: (t) => (
                <button onClick={() => setActiveTest(t)} className="font-mono text-xs font-bold text-violet-700 hover:underline text-left">
                    {t.testNo}
                </button>
            ),
        },
        {
            key: 'control',
            header: 'Kontrol',
            defaultWidth: 220,
            filter: { type: 'text', placeholder: 'Kontrol adı...', fn: (t: ControlTest, v) => (t.control.name + ' ' + t.control.controlId).toLowerCase().includes(v.toLowerCase()) },
            render: (t) => (
                <div className="min-w-0">
                    <p className="text-xs font-semibold text-slate-700 truncate">{t.control.name}</p>
                    <p className="text-[10px] text-slate-400 font-mono">{t.control.controlId}</p>
                </div>
            ),
        },
        {
            key: 'directorate',
            header: 'Direktörlük',
            sortable: true,
            defaultWidth: 160,
            filter: { type: 'text', placeholder: 'Direktörlük...', fn: (t: ControlTest, v) => (t.directorate?.name || '').toLowerCase().includes(v.toLowerCase()) },
            render: (t) => (
                <span className="text-xs text-slate-600 truncate block max-w-[150px]">{t.directorate?.name || '—'}</span>
            ),
        },
        {
            key: 'plannedDate',
            header: 'Plan Tarihi',
            sortable: true,
            defaultWidth: 110,
            render: (t) => {
                const isOverdue = ['BEKLIYOR', 'DEVAM_EDIYOR'].includes(t.status) && new Date(t.plannedDate) < new Date();
                return <span className={`text-xs font-medium ${isOverdue ? 'text-red-600' : 'text-slate-700'}`}>{fmt(t.plannedDate)}{isOverdue && ' ⚠'}</span>;
            },
        },
        {
            key: 'status',
            header: 'Statü',
            sortable: true,
            defaultWidth: 140,
            filter: { type: 'select', options: Object.entries(statusConfig).map(([k, v]) => ({ value: k, label: v.label })), fn: (t: ControlTest, v) => t.status === v },
            render: (t) => {
                const sc = statusConfig[t.status];
                const fc = t.findingStatus ? findingStatusConfig[t.findingStatus] : null;
                return (
                    <div className="flex flex-col gap-1">
                        {sc && <StatusBadge variant={sc.variant}>{sc.label}</StatusBadge>}
                        {fc && <StatusBadge variant={fc.variant} dot>{fc.label}</StatusBadge>}
                    </div>
                );
            },
        },
        {
            key: 'findings',
            header: 'Bulgular',
            defaultWidth: 80,
            render: (t) => {
                const cnt = t.findings?.length || 0;
                return cnt > 0
                    ? <span className="px-2 py-0.5 bg-red-100 text-red-700 text-xs font-bold rounded-full border border-red-200">{cnt}</span>
                    : <span className="text-slate-300 text-xs">—</span>;
            },
        },
        {
            key: 'actions',
            header: '',
            defaultWidth: 60,
            render: (t) => (
                <button onClick={() => setActiveTest(t)} className="p-1.5 text-slate-400 hover:text-violet-600 hover:bg-violet-50 rounded transition-colors" title="Aç">
                    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" /></svg>
                </button>
            ),
        },
    ], []);

    const colFiltered = useMemo(() => {
        if (!Object.values(colFilters).some(v => v)) return filtered;
        return filtered.filter(t => columns.every(col => {
            const val = colFilters[col.key];
            return !val || !col.filter?.fn || col.filter.fn(t, val);
        }));
    }, [filtered, colFilters, columns]);

    const paginated = useMemo(() => colFiltered.slice((page - 1) * pageSize, page * pageSize), [colFiltered, page]);

    // ─────────────────────────────────────────────────────────────────────────

    return (
        <div className="flex h-full bg-slate-50/50">
            {/* List Panel */}
            <div className={`flex flex-col ${activeTest ? 'flex-1' : 'w-full'} min-w-0`}>
                <div className="px-6 pt-6">
                    <PageHeader
                        title="Kontrol Testleri"
                        description="Kontrollere ait test kayıtlarını yönetin — başlatın, tamamlayın, onaylayın"
                        breadcrumbs={[{ label: 'Kontrol Testleri' }]}
                    />

                    {/* Month Filter */}
                    <div className="mb-4 bg-white border border-slate-200 rounded-xl p-3 shadow-sm">
                        <div className="flex items-center gap-1.5">
                            <span className="text-xs font-semibold text-slate-500 uppercase tracking-wide mr-2 whitespace-nowrap">📅 Ay:</span>
                            <button
                                onClick={() => { setSelectedMonth(null); setPage(1); }}
                                className={`px-3 py-1.5 rounded-lg text-xs font-semibold transition-all ${
                                    selectedMonth === null
                                        ? 'bg-violet-600 text-white shadow-sm'
                                        : 'bg-slate-100 text-slate-600 hover:bg-slate-200'
                                }`}
                            >
                                Tümü
                            </button>
                            {MONTHS_SHORT.map((m, i) => {
                                const isCurrentMonth = i === new Date().getMonth();
                                return (
                                    <button
                                        key={i}
                                        onClick={() => { setSelectedMonth(i); setPage(1); }}
                                        className={`px-2.5 py-1.5 rounded-lg text-xs font-semibold transition-all ${
                                            selectedMonth === i
                                                ? 'bg-violet-600 text-white shadow-sm'
                                                : isCurrentMonth
                                                    ? 'bg-violet-50 text-violet-700 border border-violet-200 hover:bg-violet-100'
                                                    : 'bg-slate-100 text-slate-600 hover:bg-slate-200'
                                        }`}
                                        title={MONTHS_TR[i]}
                                    >
                                        {m}
                                    </button>
                                );
                            })}
                        </div>
                    </div>

                    {/* KPIs */}
                    <div className="grid grid-cols-7 gap-2 mb-4">
                        {[
                            { label: 'Toplam', value: kpis.total, color: 'slate', onClick: () => setActiveFilters({}) },
                            { label: 'Bekliyor', value: kpis.bekliyor, color: 'slate', onClick: () => { setActiveFilters({ status: 'BEKLIYOR' }); setPage(1); } },
                            { label: 'Devam', value: kpis.devam, color: 'amber', onClick: () => { setActiveFilters({ status: 'DEVAM_EDIYOR' }); setPage(1); } },
                            { label: 'Tamamlandı', value: kpis.tamamlandi, color: 'blue', onClick: () => { setActiveFilters({ status: 'TAMAMLANDI' }); setPage(1); } },
                            { label: 'Onaylı', value: kpis.onaylandi, color: 'emerald', onClick: () => { setActiveFilters({ status: 'ONAYLANDI' }); setPage(1); } },
                            { label: 'Bulgulu', value: kpis.bulgulu, color: 'red', onClick: () => { setActiveFilters({ findingStatus: 'BULGUSU_VAR' }); setPage(1); } },
                            { label: 'Gecikmiş', value: kpis.overdue, color: 'orange', onClick: () => {} },
                        ].map(k => (
                            <button key={k.label} onClick={k.onClick}
                                className={`bg-white border border-${k.color}-100 rounded-xl p-3 text-center hover:border-${k.color}-300 hover:shadow-sm transition-all`}>
                                <p className={`text-xl font-bold text-${k.color}-700`}>{k.value}</p>
                                <p className={`text-[10px] font-semibold text-${k.color}-500 uppercase tracking-wide`}>{k.label}</p>
                            </button>
                        ))}
                    </div>

                    {/* Filter */}
                    <div className="mb-4 bg-white border border-slate-200 rounded-xl p-3 shadow-sm">
                        <FilterBar
                            searchValue={searchQuery}
                            onSearchChange={v => { setSearchQuery(v); setPage(1); }}
                            searchPlaceholder="Test No, Kontrol adı, Direktörlük ara..."
                            filters={filterConfigs}
                            onClearAll={() => { setSearchQuery(''); setActiveFilters({}); setPage(1); }}
                        />
                    </div>
                </div>

                <div className="px-6 pb-6 flex-1">
                    <DataTable
                        columns={columns}
                        data={paginated}
                        rowKey={t => t.id}
                        loading={loading}
                        totalCount={colFiltered.length}
                        page={page}
                        pageSize={pageSize}
                        onPageChange={setPage}
                        storageKey="control-tests-v1"
                        emptyTitle="Test kaydı bulunamadı"
                        emptyDescription="Kontrolleri aktif yaparak test kayıtlarını otomatik oluşturun."
                        onRowClick={t => setActiveTest(t)}
                        columnFilters={colFilters}
                        onColumnFilterChange={(k, v) => { setColFilters(p => ({ ...p, [k]: v })); setPage(1); }}
                    />
                </div>
            </div>

            {/* Workspace Panel */}
            {activeTest && (
                <div className="w-96 flex-shrink-0 border-l border-slate-200 overflow-hidden">
                    <WorkspacePanel
                        test={activeTest}
                        users={users}
                        onRefresh={() => { load(); setActiveTest(null); }}
                        onClose={() => setActiveTest(null)}
                    />
                </div>
            )}
        </div>
    );
}

export default function ControlTestingPage() {
    return (
        <Suspense fallback={<div className="p-6 text-center text-sm text-slate-500">Yükleniyor...</div>}>
            <ControlTestingPageContent />
        </Suspense>
    );
}
