import { Controller, Post } from '@nestjs/common';
import { ApiTags } from '@nestjs/swagger';
import { PrismaService } from '../../prisma';

@ApiTags('Tests Generation')
@Controller('tests')
export class TestsController {
    constructor(private prisma: PrismaService) {}

    // Legacy endpoint — tüm aktif kontroller için test oluştur
    @Post('generate')
    async generateTests() {
        try {
            const controls = await this.prisma.control.findMany({
                where: { status: 'ACTIVE' },
            });

            let generatedCount = 0;
            const now = new Date();
            const year = now.getFullYear();
            const monthNames = ['Ocak', 'Şubat', 'Mart', 'Nisan', 'Mayıs', 'Haziran', 'Temmuz', 'Ağustos', 'Eylül', 'Ekim', 'Kasım', 'Aralık'];

            for (const control of controls) {
                // Zaten auto-generated test varsa atla
                const existingCount = await this.prisma.controlTest.count({
                    where: { controlId: control.id, isAutoGenerated: true },
                });
                if (existingCount > 0) continue;

                let dueDate: Date | null = null;

                if (control.frequency === 'DAILY') {
                    dueDate = new Date(); dueDate.setDate(now.getDate() + 1);
                } else if (control.frequency === 'WEEKLY') {
                    dueDate = new Date(); dueDate.setDate(now.getDate() + 7);
                } else if (control.frequency === 'MONTHLY') {
                    dueDate = new Date(year, now.getMonth() + 1, 0);
                } else if (['QUARTERLY', 'SEMI_ANNUAL', 'ANNUAL', 'AD_HOC'].includes(control.frequency)) {
                    const currentMonthName = monthNames[now.getMonth()];
                    if (control.selectedMonths?.includes(currentMonthName)) {
                        dueDate = new Date(year, now.getMonth() + 1, 0);
                    }
                }

                if (dueDate) {
                    // testNo üret
                    const prefix = `T-${year}-`;
                    const last = await this.prisma.controlTest.findFirst({
                        where: { testNo: { startsWith: prefix } },
                        orderBy: { testNo: 'desc' },
                    });
                    let next = 1;
                    if (last) { const n = parseInt(last.testNo.split('-')[2]); if (!isNaN(n)) next = n + 1; }
                    const testNo = `${prefix}${next.toString().padStart(4, '0')}`;

                    await this.prisma.controlTest.create({
                        data: {
                            testNo,
                            controlId: control.id,
                            plannedDate: dueDate,
                            isAutoGenerated: true,
                            status: 'BEKLIYOR',
                            assigneeId: control.testPerformerId || control.ownerId,
                            directorateId: control.directorateId,
                        },
                    });
                    generatedCount++;
                }
            }

            return { success: true, message: `${generatedCount} yeni test kaydı oluşturuldu.`, generatedCount };
        } catch (error) {
            console.error('Test generation error:', error);
            throw error;
        }
    }
}
